#if defined (_WIN32)
#if defined (_DEBUG)
#pragma warning (disable : 4786)
#endif
#endif
#if defined(macintosh)
#include <types.h>
#else
#include <sys/types.h>
#endif
#include <stdio.h>
#include <time.h>
#include "merc.h"
#include "tables.h"
#include "gsn.h"

#if defined(__cplusplus)
extern "C" {
#endif


const struct taxi_type taxi_table[MAX_TAXIS] = {
{2281, 41, 65},  {1061, 81, 51},  {3609, 45, 65},  {2617, 48, 65},
{14819, 55, 65}, {14837, 63, 65}, {2942, 63, 59},  {3673, 63, 55},
{5854, 55, 55},  {1109, 63, 43},  {15265, 37, 65}, {15268, 15, 51},
{15282, 24, 51}, {15177, 24, 59}, {1149, 24, 65},  {15192, 11, 65},
{15239, 11, 59}, {1182, 11, 51},  {1188, 3, 64},   {15219, 25, 0}};

const struct worldlink_type other_links[] = {
{194166, 301932}, {194682, 301936}, {231410, 301940}, {231526, 301944},
{231642, 302096}, {231758, 302100}, {231874, 302104}, {231990, 302108},
{232106, 302260}, {232222, 302264}};

const struct worldlink_type wilds_links[] = {
{234350, 320053}, {234466, 320057}, {234582, 320209}, {234698, 320213},
{234814, 320217}, {234930, 320221}, {235046, 320373}, {235162, 320377},
{237290, 320381}, {237406, 320385}, {237522, 320537}, {237638, 32054},
{150527, 320045}, {151043, 320049}};

const struct worldlink_type godrealm_links[] = {
{153721, 340000}, {153819, 340004}, {154237, 340008}, {154335, 340012},
{154754, 340016}, {154852, 340020}, {155270, 340024}, {155368, 340028},
{154508, 340028}, {155786, 340032}, {155884, 340036}, {156302, 340040},
{156400, 340044}, {156818, 340048}, {156916, 340052}, {157014, 340056},
{157334, 340060}, {157432, 340164}, {157530, 340168}};

/* for position */
const struct position_type position_table[] = {
{"dead", "dead"},           {"mortally wounded", "mort"},
{"incapacitated", "incap"}, {"stunned", "stun"},
{"sleeping", "sleep"},      {"resting", "rest"},
{"sitting", "sit"},         {"fighting", "fight"},
{"standing", "stand"},      {NULL, NULL}};

/* for sex */
const struct sex_type sex_table[] = {
{"none"}, {"male"}, {"female"}, {"either"}, {NULL}};

/* for sizes */
const struct size_type size_table[] = {{"tiny"},
{"small"},
{"medium"},
{"large"},
{"huge",},
{"giant"},
{NULL}};

const struct flag_type act_flags[] = {
{"npc", ACT_IS_NPC, FALSE},
{"sentinel", ACT_SENTINEL, TRUE},
{"scavenger", ACT_SCAVENGER, TRUE},
{"valuable", ACT_VALUABLE, TRUE},
{"mount", ACT_MOUNT, TRUE},
{"aggressive", ACT_AGGRESSIVE, TRUE},
{"stay_area", ACT_STAY_AREA, TRUE},
{"wimpy", ACT_WIMPY, TRUE},
{"pet", ACT_PET, TRUE},
{"tailor", ACT_TAILOR, TRUE},
{"jeweler", ACT_JEWELER, TRUE},
{"stonewall", ACT_STONEWALL, TRUE},
{"fastmove", ACT_FASTMOVE, TRUE},
{"weaponsmith", ACT_WEAPONSMITH, TRUE},
{"armorsmith", ACT_ARMORSMITH, TRUE},
{"defenseless", ACT_DEFENSELESS, TRUE},
{"monster", ACT_MONSTER, TRUE},
{"cover", ACT_COVER, TRUE},
{"turret", ACT_TURRET, TRUE},
{"combatobj", ACT_COMBATOBJ, TRUE},
{"nopurge", ACT_NOPURGE, TRUE},
{"outdoors", ACT_OUTDOORS, TRUE},
{"indoors", ACT_INDOORS, TRUE},
{"soulless", ACT_SOULLESS, TRUE},
{"biggame", ACT_BIGGAME, TRUE},
{"bribe", ACT_BRIBEMOB, TRUE},
{"update_always", ACT_UPDATE_ALWAYS, TRUE},
{"changer", ACT_IS_CHANGER, TRUE},
{"noexp", ACT_NOEXP, TRUE},
{"train_novice", ACT_TRAIN_NOVICE, TRUE},
{"train_intermed", ACT_TRAIN_INTERMED, TRUE},
{"train_expert", ACT_TRAIN_EXPERT, TRUE},
{"light_sleeper", ACT_LIGHT_SLEEPER, TRUE},
{"train_master", ACT_TRAIN_MASTER, TRUE},
{"train_all", ACT_TRAIN_ALL, TRUE},
{"guard", ACT_GUARD, TRUE},
{"archer", ACT_ARCHER, TRUE},
{"stay_subarea", ACT_STAY_SUBAREA, TRUE},
{NULL, ACT_NONE, FALSE}};

const struct flag_type plr_flags[] = {{"npc", PLR_IS_NPC, FALSE},
{"antispec", PLR_ANTISPEC, FALSE},
{"gm", PLR_GM, FALSE},
{"shroud", PLR_SHROUD, FALSE},
{"ghostwalking", PLR_GHOSTWALKING, FALSE},
{"ghostbound", PLR_GHOSTBOUND, FALSE},
{"shiftstash", PLR_SHIFTSTASH, FALSE},
{"bound", PLR_BOUND, FALSE},
{"nopay", PLR_NOPAY, FALSE},
{"ascending", PLR_ASCENDING, FALSE},
{"showering", PLR_SHOWERING, FALSE},
{"hidden", PLR_HIDE, FALSE},
{"shadow", PLR_SHADOW, FALSE},
{"holylight", PLR_HOLYLIGHT, FALSE},
{"nosave", PLR_NOSAVE, FALSE},
{"boundfeet", PLR_BOUNDFEET, FALSE},
{"dead", PLR_DEAD, FALSE},
{"nofollow", PLR_NOFOLLOW, FALSE},
{"color", PLR_COLOR, FALSE},
{"room_inv", PLR_ROOMINVIS, FALSE},
{"permit", PLR_PERMIT, TRUE},
{"who_inv", PLR_WHOINVIS, FALSE},
{"log", PLR_LOG, FALSE},
{"deny", PLR_DENY, FALSE},
{"freeze", PLR_FREEZE, FALSE},
{"reroll", PLR_REROLL, FALSE},
{"noticed", PLR_NOTICED, FALSE},
{"nonote", PLR_NONOTE, FALSE},
{"deepshroud", PLR_DEEPSHROUD, FALSE},
{"demonpact", PLR_DEMONPACT, FALSE},
{"spyshield", PLR_SPYSHIELD, FALSE},
{"stasis", PLR_STASIS, FALSE},
{"sinspirit", PLR_SINSPIRIT, FALSE},
{"villain", PLR_VILLAIN, FALSE},
{"guest", PLR_GUEST, FALSE},
{"nomentor", PLR_NOMENTOR, FALSE},
{"invis", PLR_INVIS, FALSE},
{"spying", PLR_SPYING, FALSE},
{"tyrant", PLR_TYRANT, FALSE},
{"maderelic", PLR_MADERELIC, TRUE},
{"monster", PLR_MONSTER, TRUE},
{"running", PLR_RUNNING, FALSE},
{"wolfbit", PLR_WOLFBIT, FALSE},
{"ghost", PLR_GHOST, FALSE},
{"manifesting", PLR_MANIFESTING, FALSE},
{"superjumping", PLR_SUPERJUMPING, FALSE},
{"flying", PLR_FLYING, FALSE},
{"visible", PLR_VISIBLE, FALSE},
{"afterglow", PLR_AFTERGLOW, FALSE},
{"influencer", PLR_INFLUENCER, FALSE},
{NULL, PLR_NONE, FALSE}};

const struct flag_type affect_flags[] = {
{"blind", A, TRUE},        {"invisible", B, TRUE},
{"detect_evil", C, TRUE},  {"detect_invis", D, TRUE},
{"detect_magic", E, TRUE}, {"detect_hidden", F, TRUE},
{"detect_good", G, TRUE},  {"sanctuary", H, TRUE},
{"faerie_fire", I, TRUE},  {"infrared", J, TRUE},
{"taint", K, TRUE},        {"poison", M, TRUE},
{"sneak", P, TRUE},        {"hide", Q, TRUE},
{"sleep", R, TRUE},        {"charm", S, TRUE},
{"flying", T, TRUE},       {"pass_door", U, TRUE},
{"rage", V, TRUE},         {"calm", W, TRUE},
{"plague", X, TRUE},       {"weaken", Y, TRUE},
{"dark_vision", Z, TRUE},  {"berserk", aa, TRUE},
{"swim", bb, TRUE},        {"regeneration", cc, TRUE},
{"slow", dd, TRUE},        {NULL, 0, 0}};

const struct flag_type affect_flags_bit[] = {
{"blind", AFF_BLIND, TRUE},
{"flash", AFF_FLASH, TRUE},
{"protect", AFF_PROTECT, TRUE},
{"fertility", AFF_FERTILITY, TRUE},
{"deaf", AFF_DEAF, TRUE},
{"sunbless", AFF_SUNBLESS, TRUE},
{"moonbless", AFF_MOONBLESS, TRUE},
{"warbless", AFF_WARBLESS, TRUE},
{"lucky", AFF_LUCKY, TRUE},
{"unlucky", AFF_UNLUCKY, TRUE},
{"sung", AFF_SUNG, TRUE},
{"vblood", AFF_VBLOOD, TRUE},
{"berserk", AFF_BERSERK, TRUE},
{"desclock", AFF_DESCLOCK, TRUE},
{"penalty", AFF_PENALTY, TRUE},
{"bonus", AFF_BONUS, TRUE},
{"pathed", AFF_PATHED, TRUE},
{"marked", AFF_MARKED, TRUE},
{"fleshforming", AFF_FLESHFORMING, TRUE},
{"wet", AFF_WET, TRUE},
{"rerolled", AFF_REROLLED, TRUE},
{"marked2", AFF_MARKED2, TRUE},
{"unbanished", AFF_UNBANISHED, TRUE},
{"desire sensitive", AFF_DSENSITIVE, TRUE},
{"ward", AFF_WARD, TRUE},
{"weaken", AFF_WEAKEN, TRUE},
{"commute", AFF_COMMUTE, TRUE},
{"drained", AFF_DRAINED, TRUE},
{"silenced", AFF_SILENCED, TRUE},
{"grief", AFF_GRIEF, TRUE},
{"slow", AFF_SLOW, TRUE},
{"bitten", AFF_BITTEN, TRUE},
{"marked3", AFF_MARKED3, TRUE},
{"mindward", AFF_MINDWARD, TRUE},
{"burst vessel", AFF_BURSTVESSEL, TRUE},
{"vitality", AFF_VITALITY, TRUE},
{"killable_2", AFF_KILLABLE_2, TRUE},
{"doorstuck", AFF_DOORSTUCK, TRUE},
{"discredit", AFF_DISCREDIT, TRUE},
{"outcast", AFF_OUTCAST, TRUE},
{"pin", AFF_PIN, TRUE},
{"understanding", AFF_UNDERSTANDING, TRUE},
{"nounderstanding", AFF_NOUNDERSTANDING, TRUE},
{"weakened", AFF_WEAKENED, TRUE},
{"badkidnappee", AFF_BADKIDNAPPEE, TRUE},
{"gag", AFF_GAG, TRUE},
{"shield", AFF_SHIELD, TRUE},
{"experimented", AFF_EXPERIMENTED, TRUE},
{"prison", AFF_PRISON, TRUE},
{"waterbless", AFF_WATERBLESS, TRUE},
{"physical_boost", AFF_PHYS_BOOST, TRUE},
{"abducted", AFF_ABDUCTED, TRUE},
{"animal minded", AFF_ANIMALMINDED, TRUE},
{"noticed", AFF_NOTICED, TRUE},
{"nomentor", AFF_NOMENTOR, TRUE},
{"fullshield", AFF_FULLSHIELD, TRUE},
{"hospital", AFF_HOSPITAL, TRUE},
{"burst vessel", AFF_BURSTVESSEL, TRUE},
{"mad", AFF_MAD, TRUE},
{"lured", AFF_LURED, TRUE},
{"presecuted", AFF_PERSECUTED, TRUE},
{"neutralized", AFF_NEUTRALIZED, TRUE},
{"triggered", AFF_TRIGGERED, TRUE},
{"notech", AFF_NOTECH, TRUE},
{"illness", AFF_ILLNESS, TRUE},
{"arthritis", AFF_ARTHRITIS, TRUE},
{"seensuper", AFF_SEENSUPER, TRUE},
{"malady", AFF_MALADY, TRUE},
{"Lazarus", AFF_LAZARUS, TRUE},
{"frost", AFF_FROST, TRUE},
{"helmet", AFF_HELMET, TRUE},
{"stonegrip", AFF_STONE_GRIP, TRUE},
{"solidgrip", AFF_SOLID_GRIP, TRUE},
{"entangle", AFF_ENTANGLE, TRUE},
{"flash", AFF_FLASH, TRUE},
{"peace", AFF_PEACE, TRUE},
{"rush", AFF_RUSH, TRUE},
{"slush", AFF_SLUSH, TRUE},
{"buffer", AFF_BUFFER, TRUE},
{"twisted", AFF_TWISTED, TRUE},
{"mirrormist", AFF_MIRROR_OF_MIST, TRUE},
{"duplicate", AFF_DUPLICATE, TRUE},
{"phase", AFF_PHASE, TRUE},
{"ringing", AFF_RINGING, TRUE},
{"halt", AFF_HALT, TRUE},
{"confusion", AFF_CONFUSION, TRUE},
{"feather", AFF_FEATHER, TRUE},
{"faded", AFF_FADED, TRUE},
{"boil", AFF_BOIL, TRUE},
{"nullify", AFF_NULLIFY, TRUE},
{"glow", AFF_GLOW, TRUE},
{"regen", AFF_REGEN, TRUE},
{"steadfast", AFF_STEADFAST, TRUE},
{"blink", AFF_BLINK, TRUE},
{"refresh", AFF_REFRESH, TRUE},
{"strsapper", AFF_STRENGTH_SAPPER, TRUE},
{"greekfire", AFF_GREEK_FIRE, TRUE},
{"criproot", AFF_CRIPPLING_ROOTS, TRUE},
{"blindstar", AFF_BLINDING_STARS, TRUE},
{"paralyzed", AFF_PARALYZED, TRUE},
{"sleepstab", AFF_SLEEPER_STAB, TRUE},
{"blackwidow", AFF_BLACK_WIDOW, TRUE},
{"invisible", AFF_INVISIBLE, TRUE},
{"staked", AFF_STAKED, TRUE},
{"songmarch", AFF_SONG_MARCH, TRUE},
{"song", AFF_SONG, TRUE},
{"whistlewind", AFF_WHISTLE_WIND, TRUE},
{"feigndeath", AFF_FEIGN_DEATH, TRUE},
{"gbh", AFF_GBH, TRUE},
{"rearuard", AFF_REAR_GUARD_PLACEMENT, TRUE},
{"block", AFF_BLOCK, TRUE},
{"deploy", AFF_DEPLOY, TRUE},
{"shieldenhance", AFF_SHIELD_ENHANCEMENT, TRUE},
{"composure", AFF_COMPOSURE, TRUE},
{"fillme3", AFF_FILLME3, TRUE},
{"heal", AFF_HEAL, TRUE},
{"disorient", AFF_DISORIENTATION, TRUE},
{"noheal", AFF_NOHEAL, TRUE},
{"mute", AFF_MUTE, TRUE},
{"suffer", AFF_SUFFER, TRUE},
{"supertain", AFF_SUPERTAINT, TRUE},
// Curbs male fertility - Discordance
{"shootingblanks", AFF_SHOOTINGBLANKS, TRUE},
// Used to apply time limit to sex transaction
{"seekingsex", AFF_SEEKINGSEX, TRUE},
// Drops everything when timer runs out
{"timeddrop", AFF_TIMEDDROP, TRUE},
// Keeps shifter from shifting
{"stuck shifting", AFF_STUCKSHIFTER, TRUE},
// Labor pains
{"contractions", AFF_CONTRACTIONS, TRUE},
{NULL, AFF_NONE, FALSE}};

const struct flag_type off_flags[] = {
{"area_attack", A, TRUE},  {"backstab", B, TRUE},
{"bash", C, TRUE},         {"berserk", D, TRUE},
{"disarm", E, TRUE},       {"dodge", F, TRUE},
{"fade", G, TRUE},         {"fast", H, TRUE},
{"kick", I, TRUE},         {"dirt_kick", J, TRUE},
{"parry", K, TRUE},        {"rescue", L, TRUE},
{"tail", M, TRUE},         {"trip", N, TRUE},
{"crush", O, TRUE},        {"assist_all", P, TRUE},
{"assist_race", R, TRUE},  {"assist_players", S, TRUE},
{"assist_guard", T, TRUE}, {"assist_vnum", U, TRUE},
{"hunt", V, TRUE},         {NULL, 0, 0}};

const struct flag_type imm_flags[] = {
{"summon", A, TRUE},    {"charm", B, TRUE},   {"magic", C, TRUE},
{"weapon", D, TRUE},    {"bash", E, TRUE},    {"pierce", F, TRUE},
{"slash", G, TRUE},     {"fire", H, TRUE},    {"cold", I, TRUE},
{"lightning", J, TRUE}, {"acid", K, TRUE},    {"poison", L, TRUE},
{"negative", M, TRUE},  {"holy", N, TRUE},    {"energy", O, TRUE},
{"mental", P, TRUE},    {"disease", Q, TRUE}, {"drowning", R, TRUE},
{"light", S, TRUE},     {"sound", T, TRUE},   {"wood", X, TRUE},
{"silver", Y, TRUE},    {"iron", Z, TRUE},    {NULL, 0, 0}};

const struct flag_type form_flags[] = {
{"edible", FORM_EDIBLE, TRUE},
{"poison", FORM_POISON, TRUE},
{"magical", FORM_MAGICAL, TRUE},
{"instant_decay", FORM_INSTANT_DECAY, TRUE},
{"other", FORM_OTHER, TRUE},
{"animal", FORM_ANIMAL, TRUE},
{"sentient", FORM_SENTIENT, TRUE},
{"undead", FORM_UNDEAD, TRUE},
{"construct", FORM_CONSTRUCT, TRUE},
{"mist", FORM_MIST, TRUE},
{"intangible", FORM_INTANGIBLE, TRUE},
{"biped", FORM_BIPED, TRUE},
{"centaur", FORM_CENTAUR, TRUE},
{"insect", FORM_INSECT, TRUE},
{"spider", FORM_SPIDER, TRUE},
{"crustacean", FORM_CRUSTACEAN, TRUE},
{"worm", FORM_WORM, TRUE},
{"blob", FORM_BLOB, TRUE},
{"mammal", FORM_MAMMAL, TRUE},
{"bird", FORM_BIRD, TRUE},
{"reptile", FORM_REPTILE, TRUE},
{"snake", FORM_SNAKE, TRUE},
{"dragon", FORM_DRAGON, TRUE},
{"amphibian", FORM_AMPHIBIAN, TRUE},
{"fish", FORM_FISH, TRUE},
{"cold_blood", FORM_COLD_BLOOD, TRUE},
{"none", 0, TRUE},
{NULL, 0, 0}};

const struct flag_type part_flags[] = {{"head", PART_HEAD, TRUE},
{"arms", PART_ARMS, TRUE},
{"legs", PART_LEGS, TRUE},
{"heart", PART_HEART, TRUE},
{"brains", PART_BRAINS, TRUE},
{"guts", PART_GUTS, TRUE},
{"hands", PART_HANDS, TRUE},
{"feet", PART_FEET, TRUE},
{"fingers", PART_FINGERS, TRUE},
{"ear", PART_EAR, TRUE},
{"eye", PART_EYE, TRUE},
{"long_tongue", PART_LONG_TONGUE, TRUE},
{"eyestalks", PART_EYESTALKS, TRUE},
{"tentacles", PART_TENTACLES, TRUE},
{"fins", PART_FINS, TRUE},
{"wings", PART_WINGS, TRUE},
{"tail", PART_TAIL, TRUE},
{"claws", PART_CLAWS, TRUE},
{"fangs", PART_FANGS, TRUE},
{"horns", PART_HORNS, TRUE},
{"scales", PART_SCALES, TRUE},
{"tusks", PART_TUSKS, TRUE},
{NULL, 0, 0}};

const struct flag_type comm_flags[] = {
{"quiet", COMM_QUIET, TRUE},
{"deaf", COMM_DEAF, TRUE},
{"nowiz", COMM_NOWIZ, TRUE},
{"noooc", COMM_NOOOC, TRUE},
{"sparring", COMM_SPARRING, TRUE},
{"vblood", COMM_VBLOOD, TRUE},
{"running", COMM_RUNNING, TRUE},
{"nonewbie", COMM_NONEWBIE, FALSE},
{"noguide", COMM_NOGUIDE, TRUE},
{"consent", COMM_CONSENT, TRUE},
{"reported", COMM_REPORTED, TRUE},
{"compact", COMM_COMPACT, TRUE},
{"brief", COMM_BRIEF, TRUE},
{"prompt", COMM_PROMPT, TRUE},
{"combine", COMM_COMBINE, TRUE},
{"telnet_ga", COMM_TELNET_GA, TRUE},
{"blindfold", COMM_BLINDFOLD, TRUE},
{"pacifist", COMM_PACIFIST, TRUE},
{"nolegends", COMM_NOLEGEND, TRUE},
{"noemote", COMM_NOEMOTE, FALSE},
{"subdue", COMM_SUBDUE, TRUE},
{"banished", COMM_BANISHED, FALSE},
{"notell", COMM_NOTELL, FALSE},
{"nochannels", COMM_NOCHANNELS, FALSE},
{"deputy", COMM_DEPUTY, FALSE},
{"proxied", COMM_PROXIED, FALSE},
{"afk", COMM_AFK, TRUE},
{"whoinvis", COMM_WHOINVIS, TRUE},
{"notitle", COMM_NOTITLE, TRUE},
{"noleader", COMM_NOLEADER, TRUE},
{"story", COMM_STORY, TRUE},
{"notguild", COMM_STALL, TRUE},
{"mentor", COMM_MENTOR, TRUE},
{"racial", COMM_RACIAL, TRUE},
{"feeding", COMM_FEEDING, FALSE},
{"stalk", COMM_NOSTALK, FALSE},
{"autofire", COMM_AUTOFIRE, FALSE},
{"nointro", COMM_NOINTRO, FALSE},
{"helpless", COMM_HELPLESS, FALSE},
{"guarded", COMM_GUARDED, FALSE},
{"nocomms", COMM_NOCOMMS, FALSE},
{"private", COMM_PRIVATE, FALSE},
{"nofrigid", COMM_NOFRIGID, FALSE},
{"researched", COMM_RESEARCHED, FALSE},
{"boarding", COMM_BOARDING, FALSE},
{"hostile", COMM_HOSTILE, FALSE},
{"cardinal", COMM_CARDINAL, FALSE},
{"cloaked", COMM_CLOAKED, FALSE},
{"wherevis", COMM_WHEREVIS, TRUE},
{"hotspot", COMM_HOTSPOT, TRUE},
{"whereanon", COMM_WHEREANON, TRUE},
{"slow", COMM_SLOW, FALSE},
{"gag", COMM_GAG, FALSE},
{"fpacifist", COMM_FORCEDPACIFIST, FALSE},
{"cleansed", COMM_CLEANSED, FALSE},
{"empowered", COMM_EMPOWERED, FALSE},
{"shadowcloak", COMM_SHADOWCLOAK, FALSE},
{"mandrake", COMM_MANDRAKE, FALSE},
{"dreamsnared", COMM_DREAMSNARED, FALSE},
{NULL, COMM_DREAMSNARED + 1, FALSE}};

const struct flag_type mprog_flags[] = {{"act", TRIG_ACT, TRUE},
{"bribe", TRIG_BRIBE, TRUE},
{"death", TRIG_DEATH, TRUE},
{"entry", TRIG_ENTRY, TRUE},
{"fight", TRIG_FIGHT, TRUE},
{"give", TRIG_GIVE, TRUE},
{"greet", TRIG_GREET, TRUE},
{"grall", TRIG_GRALL, TRUE},
{"kill", TRIG_KILL, TRUE},
{"hpcnt", TRIG_HPCNT, TRUE},
{"random", TRIG_RANDOM, TRUE},
{"speech", TRIG_SPEECH, TRUE},
{"exit", TRIG_EXIT, TRUE},
{"exall", TRIG_EXALL, TRUE},
{"delay", TRIG_DELAY, TRUE},
{"surr", TRIG_SURR, TRUE},
{NULL, 0, TRUE}};

const struct flag_type area_flags[] = {{"none", AREA_NONE, FALSE},
{"changed", AREA_CHANGED, TRUE},
{"added", AREA_ADDED, TRUE},
{"loading", AREA_LOADING, FALSE},
{NULL, 0, 0}};

const struct flag_type sex_flags[] = {
{"male", SEX_MALE, TRUE},       {"female", SEX_FEMALE, TRUE},
{"neutral", SEX_NEUTRAL, TRUE}, {"random", 3, TRUE}, /* ROM */
{"none", SEX_NEUTRAL, TRUE},    {NULL, 0, 0}};

const struct flag_type exit_flags[] = {
{"door", EX_ISDOOR, TRUE},     {"closed", EX_CLOSED, TRUE},
{"locked", EX_LOCKED, TRUE},   {"curtains", EX_CURTAINS, TRUE},
{"nopass", EX_NOPASS, TRUE},   {"seethru", EX_SEETHRU, TRUE},
{"hard", EX_HARD, TRUE},       {"hellgate", EX_HELLGATE, TRUE},
{"noclose", EX_NOCLOSE, TRUE}, {"nolock", EX_NOLOCK, TRUE},
{"hidden", EX_HIDDEN, TRUE},   {NULL, 0, 0}};

const struct flag_type door_resets[] = {{"open and unlocked", 0, TRUE},
{"closed and unlocked", 1, TRUE},
{"closed and locked", 2, TRUE},
{NULL, 0, 0}};

const struct flag_type room_flags[] = {{"dark", ROOM_DARK, TRUE},
{"kitchen", ROOM_KITCHEN, TRUE},
{"no_mob", ROOM_NO_MOB, TRUE},
{"indoors", ROOM_INDOORS, TRUE},
{"perm", ROOM_PERM, TRUE},
{"public", ROOM_PUBLIC, TRUE},
{"locked", ROOM_LOCKED, TRUE},
{"private", ROOM_PRIVATE, TRUE},
{"safe", ROOM_SAFE, TRUE},
{"silenced", ROOM_SILENCED, TRUE},
{"invisible", ROOM_INVISIBLE, TRUE},
{"bedroom", ROOM_BEDROOM, TRUE},
{"sparring", ROOM_SPARRING, TRUE},
{"camp site", ROOM_CAMPSITE, TRUE},
{"animal home", ROOM_ANIMALHOME, TRUE},
{"noshroud", ROOM_NOSHROUD, TRUE},
{"shower", ROOM_SHOWER, TRUE},
{"lightoff", ROOM_LIGHTOFF, TRUE},
{"bank", ROOM_BANK, TRUE},
{"lighton", ROOM_LIGHTON, TRUE},
{"unlit", ROOM_UNLIT, TRUE},
{"dirtroad", ROOM_DIRTROAD, TRUE},
{"bathroom", ROOM_BATHROOM, TRUE},
{"stash", ROOM_STASH, TRUE},
{"wherevis", ROOM_WHEREVIS, TRUE},
{"commercial", ROOM_COMMERCIAL, TRUE},
{"residential", ROOM_RESIDENTIAL, TRUE},
{"landline", ROOM_LANDLINE, TRUE},
{"signalboost", ROOM_SIGNALBOOST, TRUE},
{NULL, 0, 0}};

const struct flag_type sector_flags[] = {{"street", SECT_STREET, TRUE},
{"house", SECT_HOUSE, TRUE},
{"club", SECT_CLUB, TRUE},
{"resteraunt", SECT_RESTERAUNT, TRUE},
{"shop", SECT_SHOP, TRUE},
{"tavern", SECT_TAVERN, TRUE},
{"alley", SECT_ALLEY, TRUE},
{"warehouse", SECT_WAREHOUSE, TRUE},
{"commercial", SECT_COMMERCIAL, TRUE},
{"park", SECT_PARK, TRUE},
{"tunnels", SECT_TUNNELS, TRUE},
{"cafe", SECT_CAFE, TRUE},
{"rooftop", SECT_ROOFTOP, TRUE},
{"basement", SECT_BASEMENT, TRUE},
{"hospital", SECT_HOSPITAL, TRUE},
{"bank", SECT_BANK, TRUE},
{"car", SECT_CAR, TRUE},
{"air", SECT_AIR, TRUE},
{"hellgate", SECT_HELLGATE, TRUE},
{"water", SECT_WATER, TRUE},
{"underwater", SECT_UNDERWATER, TRUE},
{"atmosphere", SECT_ATMOSPHERE, TRUE},
{"forest", SECT_FOREST, TRUE},
{"cave", SECT_CAVE, TRUE},
{"swamp", SECT_SWAMP, TRUE},
{"beach", SECT_BEACH, TRUE},
{"rocky", SECT_ROCKY, TRUE},
{"shallow", SECT_SHALLOW, TRUE},
{"sidewalk", SECT_SIDEWALK, TRUE},
{"parking", SECT_PARKING, TRUE},
{"cemetary", SECT_CEMETARY, TRUE},
{"dirt", SECT_DIRT, TRUE},
{NULL, 0, 0}};

const struct flag_type type_flags[] = {
{"light", ITEM_LIGHT, TRUE},
{"weapon", ITEM_WEAPON, TRUE},
{"perfume", ITEM_PERFUME, TRUE},
{"armor", ITEM_ARMOR, TRUE},
{"potion", ITEM_POTION, TRUE},
{"furniture", ITEM_FURNITURE, TRUE},
{"trash", ITEM_TRASH, TRUE},
{"container", ITEM_CONTAINER, TRUE},
{"drinkcontainer", ITEM_DRINK_CON, TRUE},
{"key", ITEM_KEY, TRUE},
{"keyring", ITEM_KEYRING, TRUE},
{"food", ITEM_FOOD, TRUE},
{"money", ITEM_MONEY, TRUE},
{"npccorpse", ITEM_CORPSE_NPC, TRUE},
{"pc corpse", ITEM_CORPSE_PC, FALSE},
{"fountain", ITEM_FOUNTAIN, TRUE},
{"umbrella", ITEM_UMBRELLA, TRUE},
{"portal", ITEM_PORTAL, TRUE},
{"roomkey", ITEM_ROOM_KEY, TRUE},
{"ranged", ITEM_RANGED, TRUE},
{"jewelry", ITEM_JEWELRY, TRUE},
{"jukebox", ITEM_JUKEBOX, TRUE},
{"game", ITEM_GAME, TRUE},
{"component", ITEM_COMPONENT, TRUE},
{"flashlight", ITEM_FLASHLIGHT, TRUE},
{"stake", ITEM_STAKE, TRUE},
{"lighter", ITEM_LIGHTER, TRUE},
{"bloodcrystal", ITEM_BLOODCRYSTAL, TRUE},
{"artifact", ITEM_ARTIFACT, TRUE},
{"phone", ITEM_PHONE, TRUE},
{"drugs", ITEM_DRUGS, TRUE},
{"baby", ITEM_BABY, FALSE},
{"clothing", ITEM_CLOTHING, TRUE},
{NULL, 0, 0}};

const struct flag_type extra_flags[] = {
{"amulet", ITEM_AMULET, TRUE},
{"off", ITEM_OFF, TRUE},
{"vblood", ITEM_VBLOOD, TRUE},
{"lock", ITEM_LOCK, TRUE},
{"artifactweapon", ITEM_ARTIFACTWEAPON, TRUE},
{"invis", ITEM_INVIS, TRUE},
{"charm", ITEM_CHARM, TRUE},
{"nodrop", ITEM_NODROP, TRUE},
{"wardrobe", ITEM_WARDROBE, TRUE},
{"scuba", ITEM_SCUBA, TRUE},
{"collar", ITEM_COLLAR, TRUE},
{"focus", ITEM_FOCUS, TRUE},
{"silent", ITEM_SILENT, TRUE},
{"inventory", ITEM_INVENTORY, TRUE},
{"relic", ITEM_RELIC, TRUE},
{"rohypnol", ITEM_ROHYPNOL, TRUE},
{"poison", ITEM_POISON, TRUE},
{"noinventory", ITEM_NOINVENTORY, TRUE},
{"nooutfit", ITEM_NOOUTFIT, TRUE},
{"nodecay", ITEM_NODECAY, TRUE},
{"meltdrop", ITEM_NORESALE, TRUE},
{"altered", ITEM_ALTERED, TRUE},
{"hadtimer", ITEM_USABLE, TRUE},
{"shroud", ITEM_SHROUD, TRUE},
{"large", ITEM_LARGE, TRUE},
{"cursed", ITEM_CURSED, TRUE},
{"hidden", ITEM_HIDDEN, TRUE},
{"ammochanged", ITEM_AMMOCHANGED, TRUE},
{"rottimer", ITEM_ROT_TIMER, TRUE},
{"waterproof", ITEM_WATERPROOF, TRUE},
{"armored", ITEM_ARMORED, TRUE},
{NULL, 0, 0}};

const struct flag_type wear_flags[] = {{"take", ITEM_TAKE, TRUE},

{"neck", ITEM_WEAR_NECK, TRUE},
{"body", ITEM_WEAR_BODY, TRUE},
{"head", ITEM_WEAR_HEAD, TRUE},
{"legs", ITEM_WEAR_LEGS, TRUE},
{"feet", ITEM_WEAR_FEET, TRUE},
{"hands", ITEM_WEAR_HANDS, TRUE},
{"accessory", ITEM_WEAR_ACCES, TRUE},
{"hold", ITEM_HOLD, TRUE},
{"nosac", ITEM_NO_SAC, TRUE},
{"eyes", ITEM_WEAR_EYES, TRUE},
{"hole", ITEM_WEAR_HOLE, TRUE},
{NULL, 0, 0}};

/*
* Used when adding an affect to tell where it goes.
* See addaffect and delaffect in act_olc.c
*/
const struct flag_type apply_flags[] = {
{"none", APPLY_NONE, TRUE},
{"strength", APPLY_STR, TRUE},
{"speed", APPLY_SPE, TRUE},
{"martialarts", APPLY_MART, TRUE},
{"generalmagic", APPLY_MGEN, TRUE},
{"magicendurance", APPLY_MEND, TRUE},
{"mentalmagic", APPLY_MIND, TRUE},
{"demonoffense", APPLY_DOFF, TRUE},
{"demonbuff", APPLY_DBUFF, TRUE},
{"demonmystical", APPLY_DMYS, TRUE},
{"researching", APPLY_REA, TRUE},
{"alignedmagic", APPLY_MALI, TRUE},
{"weaponassembly", APPLY_WASS, TRUE},
{"weaponskill", APPLY_WSK, TRUE},
{"vitality", APPLY_VIT, TRUE},
{"sex", APPLY_SEX, TRUE},
{"class", APPLY_CLASS, TRUE},
{"level", APPLY_LEVEL, TRUE},
{"age", APPLY_AGE, TRUE},
{"height", APPLY_HEIGHT, TRUE},
{"weight", APPLY_WEIGHT, TRUE},
{"mana", APPLY_MANA, TRUE},
{"hp", APPLY_HIT, TRUE},
{"move", APPLY_MOVE, TRUE},
{"gold", APPLY_GOLD, TRUE},
{"experience", APPLY_EXP, TRUE},
{"ac", APPLY_AC, TRUE},
{"hitroll", APPLY_HITROLL, TRUE},
{"damroll", APPLY_DAMROLL, TRUE},
{"saves", APPLY_SAVES, TRUE},
{"savingpara", APPLY_SAVING_PARA, TRUE},
{"savingrod", APPLY_SAVING_ROD, TRUE},
{"savingpetri", APPLY_SAVING_PETRI, TRUE},
{"savingbreath", APPLY_SAVING_BREATH, TRUE},
{"savingspell", APPLY_SAVING_SPELL, TRUE},
{"spellaffect", APPLY_SPELL_AFFECT, FALSE},
{"comfort", APPLY_SECONDARY_COMFORT, TRUE},
{"agility", APPLY_SECONDARY_AGILITY, TRUE},
{"awareness", APPLY_SECONDARY_AWARENESS, TRUE},
{"concealment", APPLY_SECONDARY_CONCEALMENT, TRUE},
{"encomberance", APPLY_SECONDARY_ENCUMBRANCE, TRUE},
{"balance", APPLY_SECONDARY_BALANCE, TRUE},
{"adrenaline", APPLY_SECONDARY_ADRENALINE, TRUE},
{"fear", APPLY_SECONDARY_FEAR, TRUE},
{"reflexes", APPLY_SECONDARY_REFLEXES, TRUE},
{"initiative", APPLY_SECONDARY_INITIATIVE, TRUE},
{"health", APPLY_SECONDARY_HEALTH, TRUE},
{"luck", APPLY_SECONDARY_LUCK, TRUE},
{"torso ac", APPLY_TORSO_AC, TRUE},
{"head ac", APPLY_HEAD_AC, TRUE},
{"poison", APPLY_POISON, TRUE},
{"poison", APPLY_POISON_DAMAGE, TRUE},
{NULL, 0, 0}};

/*
* What is seen.
*/
const struct flag_type wear_loc_strings[] = {
{"in the inventory", WEAR_NONE, TRUE},

{"worn", WEAR_BODY_1, TRUE},
{"worn", WEAR_BODY_2, TRUE},
{"worn", WEAR_BODY_3, TRUE},
{"worn", WEAR_BODY_4, TRUE},
{"worn", WEAR_BODY_5, TRUE},
{"worn", WEAR_BODY_6, TRUE},
{"worn", WEAR_BODY_7, TRUE},
{"worn", WEAR_BODY_8, TRUE},
{"worn", WEAR_BODY_9, TRUE},
{"worn", WEAR_BODY_10, TRUE},
{"worn", WEAR_BODY_11, TRUE},
{"worn", WEAR_BODY_12, TRUE},
{"worn", WEAR_BODY_13, TRUE},
{"worn", WEAR_BODY_14, TRUE},
{"worn", WEAR_BODY_15, TRUE},
{"worn", WEAR_BODY_16, TRUE},
{"worn", WEAR_BODY_17, TRUE},
{"worn", WEAR_BODY_18, TRUE},
{"worn", WEAR_BODY_19, TRUE},
{"worn", WEAR_BODY_20, TRUE},
{"worn", WEAR_BODY_21, TRUE},
{"worn", WEAR_BODY_22, TRUE},
{"worn", WEAR_BODY_23, TRUE},
{"worn", WEAR_BODY_24, TRUE},
{"worn", WEAR_BODY_25, TRUE},
{"held in hand", WEAR_HOLD, TRUE},
{"held in offhand", WEAR_HOLD_2, TRUE},
{NULL, 0, 0}};

const struct flag_type wear_loc_flags[] = {{"none", WEAR_NONE, TRUE},
{"body1", WEAR_BODY_1, TRUE},
{"body2", WEAR_BODY_2, TRUE},
{"body3", WEAR_BODY_3, TRUE},
{"body4", WEAR_BODY_4, TRUE},
{"body5", WEAR_BODY_5, TRUE},
{"body6", WEAR_BODY_6, TRUE},
{"body7", WEAR_BODY_7, TRUE},
{"body8", WEAR_BODY_8, TRUE},
{"body9", WEAR_BODY_9, TRUE},
{"body10", WEAR_BODY_10, TRUE},
{"body11", WEAR_BODY_11, TRUE},
{"body12", WEAR_BODY_12, TRUE},
{"body13", WEAR_BODY_13, TRUE},
{"body14", WEAR_BODY_14, TRUE},
{"body15", WEAR_BODY_15, TRUE},
{"body16", WEAR_BODY_16, TRUE},
{"body17", WEAR_BODY_17, TRUE},
{"body18", WEAR_BODY_18, TRUE},
{"body19", WEAR_BODY_19, TRUE},
{"body20", WEAR_BODY_20, TRUE},
{"body21", WEAR_BODY_21, TRUE},
{"body22", WEAR_BODY_22, TRUE},
{"body23", WEAR_BODY_23, TRUE},
{"body24", WEAR_BODY_24, TRUE},
{"body25", WEAR_BODY_25, TRUE},

{"hold", WEAR_HOLD, TRUE},
{"hold2", WEAR_HOLD_2, TRUE},
{NULL, 0, 0}};

const struct flag_type container_flags[] = {{"closeable", 1, TRUE},
{"pickproof", 2, TRUE},
{"closed", 4, TRUE},
{"locked", 8, TRUE},
{"puton", 16, TRUE},
{"lockable", 32, TRUE},
{NULL, 0, 0}};

/*****************************************************************************
ROM - specific tables:
****************************************************************************/

const struct flag_type ac_type[] = {{"pierce", AC_PIERCE, TRUE},
{"bash", AC_BASH, TRUE},
{"slash", AC_SLASH, TRUE},
{"exotic", AC_EXOTIC, TRUE},
{NULL, 0, 0}};

const struct flag_type size_flags[] = {
{"tiny", SIZE_TINY, TRUE},
{"small", SIZE_SMALL, TRUE},
{"medium", SIZE_MEDIUM, TRUE},
{"large", SIZE_LARGE, TRUE},
{"huge", SIZE_HUGE, TRUE},
{"giant", SIZE_GIANT, TRUE},
{NULL, 0, 0},
};

const struct flag_type weapon_class[] = {{"exotic", WEAPON_EXOTIC, TRUE},
{"sword", WEAPON_SWORD, TRUE},
{"dagger", WEAPON_DAGGER, TRUE},
{"spear", WEAPON_SPEAR, TRUE},
{"mace", WEAPON_MACE, TRUE},
{"axe", WEAPON_AXE, TRUE},
{"flail", WEAPON_FLAIL, TRUE},
{"fist", WEAPON_FIST, TRUE},
{"staff", WEAPON_STAFF, TRUE},
{"polearm", WEAPON_POLEARM, TRUE},
{NULL, 0, 0}};

const struct flag_type weapon_type2[] = {{"flaming", WEAPON_FLAMING, TRUE},
{"frost", WEAPON_FROST, TRUE},
{"vampiric", WEAPON_VAMPIRIC, TRUE},
{"sharp", WEAPON_SHARP, TRUE},
{"vorpal", WEAPON_VORPAL, TRUE},
{"twohands", WEAPON_TWO_HANDS, TRUE},
{"shocking", WEAPON_SHOCKING, TRUE},
{"poison", WEAPON_POISON, TRUE},
{NULL, 0, 0}};

const struct flag_type res_flags[] = {
{"summon", RES_SUMMON, TRUE},     {"charm", RES_CHARM, TRUE},
{"magic", RES_MAGIC, TRUE},       {"weapon", RES_WEAPON, TRUE},
{"bash", RES_BASH, TRUE},         {"pierce", RES_PIERCE, TRUE},
{"slash", RES_SLASH, TRUE},       {"fire", RES_FIRE, TRUE},
{"cold", RES_COLD, TRUE},         {"lightning", RES_LIGHTNING, TRUE},
{"acid", RES_ACID, TRUE},         {"poison", RES_POISON, TRUE},
{"negative", RES_NEGATIVE, TRUE}, {"holy", RES_HOLY, TRUE},
{"energy", RES_ENERGY, TRUE},     {"mental", RES_MENTAL, TRUE},
{"disease", RES_DISEASE, TRUE},   {"drowning", RES_DROWNING, TRUE},
{"light", RES_LIGHT, TRUE},       {"sound", RES_SOUND, TRUE},
{"wood", RES_WOOD, TRUE},         {"silver", RES_SILVER, TRUE},
{"iron", RES_IRON, TRUE},         {NULL, 0, 0}};

const struct flag_type vuln_flags[] = {
{"summon", VULN_SUMMON, TRUE},     {"charm", VULN_CHARM, TRUE},
{"magic", VULN_MAGIC, TRUE},       {"weapon", VULN_WEAPON, TRUE},
{"bash", VULN_BASH, TRUE},         {"pierce", VULN_PIERCE, TRUE},
{"slash", VULN_SLASH, TRUE},       {"fire", VULN_FIRE, TRUE},
{"cold", VULN_COLD, TRUE},         {"lightning", VULN_LIGHTNING, TRUE},
{"acid", VULN_ACID, TRUE},         {"poison", VULN_POISON, TRUE},
{"negative", VULN_NEGATIVE, TRUE}, {"holy", VULN_HOLY, TRUE},
{"energy", VULN_ENERGY, TRUE},     {"mental", VULN_MENTAL, TRUE},
{"disease", VULN_DISEASE, TRUE},   {"drowning", VULN_DROWNING, TRUE},
{"light", VULN_LIGHT, TRUE},       {"sound", VULN_SOUND, TRUE},
{"wood", VULN_WOOD, TRUE},         {"silver", VULN_SILVER, TRUE},
{"iron", VULN_IRON, TRUE},         {NULL, 0, 0}};

const struct flag_type position_flags[] = {
{"dead", POS_DEAD, FALSE},        {"mortal", POS_MORTAL, FALSE},
{"incap", POS_INCAP, FALSE},      {"stunned", POS_STUNNED, FALSE},
{"sleeping", POS_SLEEPING, TRUE}, {"resting", POS_RESTING, TRUE},
{"sitting", POS_SITTING, TRUE},   {"fighting", POS_FIGHTING, FALSE},
{"standing", POS_STANDING, TRUE}, {NULL, 0, 0}};

const struct flag_type portal_flags[] = {
{"normal_exit", GATE_NORMAL_EXIT, TRUE}, {"no_curse", GATE_NOCURSE, TRUE},
{"go_with", GATE_GOWITH, TRUE},          {"buggy", GATE_BUGGY, TRUE},
{"random", GATE_RANDOM, TRUE},           {NULL, 0, 0}};

const struct flag_type furniture_flags[] = {{"stand_at", STAND_AT, TRUE},
{"stand_on", STAND_ON, TRUE},
{"stand_in", STAND_IN, TRUE},
{"sit_at", SIT_AT, TRUE},
{"sit_on", SIT_ON, TRUE},
{"sit_in", SIT_IN, TRUE},
{"rest_at", REST_AT, TRUE},
{"rest_on", REST_ON, TRUE},
{"rest_in", REST_IN, TRUE},
{"sleep_at", SLEEP_AT, TRUE},
{"sleep_on", SLEEP_ON, TRUE},
{"sleep_in", SLEEP_IN, TRUE},
{"put_at", PUT_AT, TRUE},
{"put_on", PUT_ON, TRUE},
{"put_in", PUT_IN, TRUE},
{"put_inside", PUT_INSIDE, TRUE},
{NULL, 0, 0}};

const struct flag_type apply_types[] = {{"affects", TO_AFFECTS, TRUE},
{"object", TO_OBJECT, TRUE},
{"immune", TO_IMMUNE, TRUE},
{"resist", TO_RESIST, TRUE},
{"vuln", TO_VULN, TRUE},
{"weapon", TO_WEAPON, TRUE},
{NULL, 0, TRUE}};

const struct bit_type bitvector_type[] = {
{affect_flags, "affect"}, {apply_flags, "apply"}, {imm_flags, "imm"},
{res_flags, "res"},       {vuln_flags, "vuln"},   {weapon_type2, "weapon"}};

const struct flag_type oprog_flags[] = {
{"act", TRIG_ACT, TRUE},       {"fight", TRIG_FIGHT, TRUE},
{"give", TRIG_GIVE, TRUE},     {"grall", TRIG_GRALL, TRUE},
{"random", TRIG_RANDOM, TRUE}, {"speech", TRIG_SPEECH, TRUE},
{"exall", TRIG_EXALL, TRUE},   {"delay", TRIG_DELAY, TRUE},
{"drop", TRIG_DROP, TRUE},     {"get", TRIG_GET, TRUE},
{"sit", TRIG_SIT, TRUE},       {NULL, 0, TRUE},
};

const struct flag_type rprog_flags[] = {
{"act", TRIG_ACT, TRUE},
{"fight", TRIG_FIGHT, TRUE},
{"drop", TRIG_DROP, TRUE},
{"grall", TRIG_GRALL, TRUE},
{"random", TRIG_RANDOM, TRUE},
{"speech", TRIG_SPEECH, TRUE},
{"exall", TRIG_EXALL, TRUE},
{"delay", TRIG_DELAY, TRUE},
{NULL, 0, TRUE},
};

const char *comm_table[] = {
"Quiet",        "Deaf",     "Wiz",      "OOC",      "Gossip",
"Quest",        "Clan",     "Newbie",

"Guide",        "Auction",  "Bond",

"Compact",      "Brief",    "Prompt",   "Combine",  "TELNET_GA",
"Show Affects", "Hero",     "Minion",   "Hint",     "Emote",
"Yell",         "Tell",     "Channels", "Imp",      "Snoop Proof",
"AFK",          "Coding",   "Guild",    "Building", "SGuild",
"TGuild",       "Roleplay", "Mission",  "NPC",      "None"};

/* item type list */
const struct item_type item_table[] = {
{ITEM_LIGHT, "light"},
{ITEM_WEAPON, "weapon"},
{ITEM_PERFUME, "perfume"},
{ITEM_ARMOR, "armor"},
{ITEM_POTION, "potion"},
{ITEM_CLOTHING, "clothing"},
{ITEM_FURNITURE, "furniture"},
{ITEM_TRASH, "trash"},
{ITEM_CONTAINER, "container"},
{ITEM_DRINK_CON, "drink"},
{ITEM_KEY, "key"},
{ITEM_FOOD, "food"},
{ITEM_MONEY, "money"},
{ITEM_CORPSE_NPC, "npc_corpse"},
{ITEM_CORPSE_PC, "pc_corpse"},
{ITEM_FOUNTAIN, "fountain"},
{ITEM_UMBRELLA, "umbrella"},
{ITEM_ROOM_KEY, "room_key"},
{ITEM_RANGED, "ranged"},
{ITEM_JEWELRY, "jewelry"},
{ITEM_JUKEBOX, "jukebox"},
{ITEM_KEYRING, "keyring"},
{ITEM_GAME, "game"},
{ITEM_COMPONENT, "component"},
{ITEM_FLASHLIGHT, "flashlight"},
{ITEM_STAKE, "stake"},
{ITEM_LIGHTER, "lighter"},
{ITEM_BLOODCRYSTAL, "bloodcrystal"},
{ITEM_ARTIFACT, "artifact"},
{ITEM_PHONE, "phone"},
{ITEM_DRUGS, "drugs"},
{ITEM_BABY, "baby"},
{0, NULL}};

/* wiznet table and prototype for future flag setting */
const struct wiznet_type wiznet_table[] = {
{"on", WIZ_ON, IMMORTAL},
{"prefix", WIZ_PREFIX, IMMORTAL},
{"ticks", WIZ_TICKS, ADMIN},
{"logins", WIZ_LOGINS, LEVEL_RESIDENT},
{"sites", WIZ_SITES, ADMIN},
{"links", WIZ_LINKS, LEVEL_RESIDENT},
{"newbies", WIZ_NEWBIE, JUNIOR},
{"spam", WIZ_SPAM, JUNIOR},
{"deaths", WIZ_DEATHS, JUNIOR},
{"resets", WIZ_RESETS, JUNIOR},
{"mobdeaths", WIZ_MOBDEATHS, JUNIOR},
{"flags", WIZ_FLAGS, JUNIOR},
{"penalties", WIZ_PENALTIES, JUNIOR},
{"saccing", WIZ_SACCING, JUNIOR},
{"levels", WIZ_LEVELS, LEVEL_RESIDENT},
{"load", WIZ_LOAD, IMMORTAL},
{"restore", WIZ_RESTORE, ADMIN},
{"snoops", WIZ_SNOOPS, IMPLEMENTOR},
{"switches", WIZ_SWITCHES, ADMIN},
{"secure", WIZ_SECURE, ADMIN},
{"info", WIZ_INFO, ADMIN},
{"etimers", WIZ_ETIMER, LEVEL_RESIDENT},
{NULL, 0, 0}};

/*
* Illegal name table
* Enter in any name that cannot be used here.
* Enjoy - Palin
*/
const char *iname_table[MAX_INAME] = {
/* Forsaken */
"Asmodean", "Balthamel", "Belal", "Demandred", "Graendal", "Ishamael",
"Lanfear", "Mesaana", "Moghedien", "Rahvin", "Sammael", "Semirhage",

/* WoT - Main Characters */
"Mat", "Perrin", "Rand", "Min", "Padan", "Fain", "Rhuarc", "Amys", "Egwene",
"Nynaeve", "Siuan", "Leane", "Moiraine", "Lan", "Aviendha", "Cadsuane",
"Galad", "Gawyn", "Faile", "Bashere", "Narishma", "Logain", "Sheriam",
"Mazrim", "Taim", "Elaida", "Alviarin"};

/*
* Liquid properties.
* Used in world.obj.
*/
const struct liq_type liq_table[] = {
/*    name			color	proof, full, thirst, food, ssize */
{"water", "clear", {0, 1, 10, 0, 16}},
{"beer", "amber", {2, 1, 8, 1, 12}},
{"red wine", "burgundy", {2, 1, 8, 1, 5}},
{"ale", "brown", {2, 1, 8, 1, 12}},
{"dark ale", "dark", {2, 1, 8, 1, 12}},

{"whisky", "golden", {10, 1, 5, 0, 2}},
{"lemonade", "pink", {0, 1, 9, 2, 12}},
{"firebreather", "boiling", {190, 0, 4, 0, 2}},
{"local specialty", "clear", {151, 1, 3, 0, 2}},
{"slime mold juice", "green", {0, 2, -8, 1, 2}},

{"milk", "white", {0, 2, 9, 3, 12}},
{"tea", "tan", {0, 1, 8, 0, 6}},
{"coffee", "black", {0, 1, 8, 0, 6}},
{"blood", "red", {0, 2, -1, 2, 6}},
{"salt water", "clear", {0, 1, -2, 0, 1}},

{"coke", "brown", {0, 2, 9, 2, 12}},
{"root beer", "brown", {0, 2, 9, 2, 12}},
{"elvish wine", "green", {35, 2, 8, 1, 5}},
{"white wine", "golden", {28, 1, 8, 1, 5}},
{"champagne", "golden", {32, 1, 8, 1, 5}},

{"mead", "honey-colored", {34, 2, 8, 2, 12}},
{"rose wine", "pink", {26, 1, 8, 1, 5}},
{"benedictine wine", "burgundy", {40, 1, 8, 1, 5}},
{"vodka", "clear", {130, 1, 5, 0, 2}},
{"cranberry juice", "red", {0, 1, 9, 2, 12}},

{"orange juice", "orange", {0, 2, 9, 3, 12}},
{"absinthe", "green", {200, 1, 4, 0, 2}},
{"brandy", "golden", {80, 1, 5, 0, 4}},
{"aquavit", "clear", {140, 1, 5, 0, 2}},
{"schnapps", "clear", {90, 1, 5, 0, 2}},

{"icewine", "purple", {50, 2, 6, 1, 5}},
{"amontillado", "burgundy", {35, 2, 8, 1, 5}},
{"sherry", "red", {38, 2, 7, 1, 5}},
{"framboise", "red", {50, 1, 7, 1, 5}},
{"rum", "amber", {151, 1, 4, 0, 2}},

{"cordial", "clear", {100, 1, 5, 0, 2}},
{"rocket fuel", "clear", {500, 2, 2, 2, 2}},
{NULL, NULL, {0, 0, 0, 0, 0}}};

/*
* Help File Type Table
*/
const char *hfile_type_table[MAX_HFILE_TYPE] = {
"Other", "Immortal", "Skill", "Command", "Class", "Race", "Weave", "Form"
};

const int cover_table[MAX_COVERS] = {
COVERS_HANDS,
COVERS_LOWER_ARMS,
COVERS_UPPER_ARMS,
COVERS_FEET,
COVERS_LOWER_LEGS,
COVERS_FOREHEAD,
COVERS_THIGHS,
COVERS_GROIN,
COVERS_ARSE,
COVERS_LOWER_BACK,
COVERS_UPPER_BACK,
COVERS_LOWER_CHEST,
COVERS_BREASTS,
COVERS_UPPER_CHEST,
COVERS_NECK,
COVERS_LOWER_FACE,
COVERS_HAIR,
COVERS_EYES
};

// more pretty columns; maybe will fix the rest above later - Disco
const int contacts_table[MAX_CONTACTS] = {
SKILL_CPOLICE,   SKILL_CMILITARY, SKILL_CGOVERNMENT, SKILL_CMEDIA,
SKILL_CCRIMINAL, SKILL_COCCULT,   SKILL_CHOMELESS,   SKILL_CHAND,
SKILL_CORDER,    SKILL_CTEMPLE,   SKILL_CSUBFACTION};

const struct district_type district_table[] = {
{DIST_BROWN,     "BrownUniversity", "brown",       0,     0, 0},
{DIST_BOSTON,    "Boston",          "bst",       -25,   -25, 0},
{DIST_AMERICA,   "America",         "usa",     -1600,  -200, 0},
{DIST_MEXICO,    "Mexico",          "mex",     -1900, -1900, 0},
{DIST_CANADA,    "Canada",          "can",     -1600,  1600, 0},
{DIST_SAMERICA,  "SouthAmerica",    "samerica", 1300, -2500, 0},
{DIST_EUROPE,    "Europe",          "euro",     3900,   500, 0},
{DIST_AFRICA,    "Africa",          "afri",     3900, -1900, 0},
{DIST_ASIA,      "Asia",            "asia",     6500,  -800, 0},
{DIST_AUSTRALIA, "Australia",       "aus",      8000, -3000, 0},
{DIST_MISTS,     "Mists",           "mists",       0,     0, 0},
{DIST_OTHER,     "Other",           "other",       0,     0, 0},
{DIST_GODREALM,  "Godrealm",        "godrealm",    0,     0, 0},
{DIST_WILDS,     "Wilds",           "wilds",       0,     0, 0},
{DIST_DREAM,     "Dreamscape",      "dream",       0,     0, 0}
};

const int room_list[] = {31000, 32000, 33000, 34000, 35000, 36000, 37000, 38000, 39000, 40000, 41000};

// name, whoname, pc, create, vnum, tier, super, changeto, minage, maxage, min_a_age, max_a_age
// referenced by functions min_aage, min_age, max_aage, max_age
const struct race_type race_table[] = {
{"civilian",         "`wInnocent`x",          FALSE, FALSE, RACE_CIVILIAN,        1, FALSE,  TRUE,  18,    80, 18,   80},
{"local",            "`wLocal`x",              TRUE,  TRUE, RACE_LOCAL,           1, FALSE,  TRUE,  18,    80, 18,   80},
{"visitor",          "`wVisitor`x",            TRUE,  TRUE, RACE_VISITOR,         1, FALSE,  TRUE,  18,    80, 18,   80},
{"student",          "`wStudent`x",            TRUE,  TRUE, RACE_STUDENT,         1, FALSE,  TRUE,  18,    60, 18,   60},
{"soldier",          "`cSoldier`x",            TRUE,  TRUE, RACE_SOLDIER,         2, FALSE,  TRUE,  18,    50, 18,   50},
{"timeswept",        "`cTimeswept`x",          TRUE,  TRUE, RACE_TIMESWEPT,       2, FALSE, FALSE,  18,    80, 18,   80},
{"wildling",         "`cWildling`x",           TRUE,  TRUE, RACE_WILDLING,        2, FALSE, FALSE,  18,    80, 18,   80},
{"brown",            "`cBrown Student`x",      TRUE,  TRUE, RACE_BROWN,           2, FALSE,  TRUE,  18,    60, 18,   60},
{"important",        "`cImportant Local`x",    TRUE,  TRUE, RACE_IMPORTANT,       2, FALSE,  TRUE,  24,    80, 24,   80},
{"deputy",           "`cSpecial Deputy`x",     TRUE,  TRUE, RACE_DEPUTY,          2, FALSE,  TRUE,  22,    50, 22,   50},
{"newvampire",       "`DVampire`x",            TRUE,  TRUE, RACE_NEWVAMPIRE,      2,  TRUE,  TRUE,  18,    70, 18,   50},
{"newwerewolf",      "`yWerewolf`x",           TRUE,  TRUE, RACE_NEWWEREWOLF,     2,  TRUE,  TRUE,  18,    50, 18,   50},
{"newfaeborn",       "`gFaeborn`x",            TRUE,  TRUE, RACE_NEWFAEBORN,      2,  TRUE,  TRUE,  18,    50, 18,   50},
{"newangelborn",     "`WAngelborn`x",          TRUE,  TRUE, RACE_NEWANGELBORN,    2,  TRUE,  TRUE,  18,    50, 18,   50},
{"newdemonborn",     "`rDemonborn`x",          TRUE,  TRUE, RACE_NEWDEMONBORN,    2,  TRUE,  TRUE,  18,    50, 18,   50},
{"newdemigod",       "`CDemigod`x",            TRUE,  TRUE, RACE_NEWDEMIGOD,      2,  TRUE,  TRUE,  18,    50, 18,   50},
{"gifted",           "`YGifted`x",             TRUE,  TRUE, RACE_GIFTED,          2, FALSE,  TRUE,  25,    80, 25,   80},
{"specialforces",    "`cSpecial Forces`x",     TRUE,  TRUE, RACE_SFORCES,         3, FALSE, FALSE,  30,    50, 30,   50},
{"celebrity",        "`cLocal Celebrity`x",    TRUE,  TRUE, RACE_CELEBRITY,       3, FALSE, FALSE,  18,    50, 18,   50},
{"pillar",           "`cCommunity Pillar`x",   TRUE,  TRUE, RACE_PILLAR,          3, FALSE, FALSE,  28,    80, 28,   80},
{"veteranvampire",   "`DVeteran Vampire`x",    TRUE,  TRUE, RACE_VETVAMPIRE,      3,  TRUE, FALSE,  58,   200, 18,   60},
{"veteranwerewolf",  "`yVeteran Werewolf`x",   TRUE,  TRUE, RACE_VETWEREWOLF,     3,  TRUE, FALSE,  28,    80, 23,   80},
{"veteranfaeborn",   "`gFaeborn Veteran`x",    TRUE,  TRUE, RACE_VETFAEBORN,      3,  TRUE, FALSE,  28,    80, 21,   80},
{"veteranangelborn", "`WAngelborn Veteran`x",  TRUE,  TRUE, RACE_VETANGELBORN,    3,  TRUE, FALSE,  28,    80, 23,   80},
{"veterandemonborn", "`rDemonborn Veteran`x",  TRUE,  TRUE, RACE_VETDEMONBORN,    3,  TRUE, FALSE,  28,    80, 23,   80},
{"veterandemigod",   "`CDemigod Veteran`x",    TRUE,  TRUE, RACE_VETDEMIGOD,      3,  TRUE, FALSE,  28,    80, 21,   80},
{"veterangifted",    "`YGifted Veteran`x",     TRUE, FALSE, RACE_VETGIFTED,       3,  TRUE, FALSE,  28,    80, 28,   80},
{"oldvampire",       "`DAged Vampire`x",       TRUE,  TRUE, RACE_OLDVAMPIRE,      4,  TRUE, FALSE,  208,  880, 18,   60},
{"oldwerewolf",      "`yAgeless Werewolf`x",   TRUE,  TRUE, RACE_OLDWEREWOLF,     4,  TRUE, FALSE,  100,  250, 21,   70},
{"oldfaeborn",       "`gAgeless Faeborn`x",    TRUE,  TRUE, RACE_OLDFAEBORN,      4,  TRUE, FALSE,  100,  250, 23,   70},
{"oldangelborn",     "`WAgeless Angelborn`x",  TRUE,  TRUE, RACE_OLDANGELBORN,    4,  TRUE, FALSE,  100,  250, 23,   70},
{"olddemonborn",     "`rAgeless Demonborn`x",  TRUE,  TRUE, RACE_OLDDEMONBORN,    4,  TRUE, FALSE,  100,  250, 23,   70},
{"olddemigod",       "`CAgeless Demigod`x",    TRUE,  TRUE, RACE_OLDDEMIGOD,      4,  TRUE, FALSE,  100,  250, 23,   70},
{"ancientvampire",   "`DAncient Vampire`x",    TRUE,  TRUE, RACE_ANCIENTVAMPIRE,  5,  TRUE, FALSE, 1008, 4000, 18,   60},
{"ancientwerewolf",  "`yAncient Werewolf`x",   TRUE,  TRUE, RACE_ANCIENTWEREWOLF, 5,  TRUE, FALSE, 3000, 5000, 30,   70},
{"demidemon",        "`RDemiDemon`x",          TRUE,  TRUE, RACE_DEMIDEMON,       5,  TRUE, FALSE,  100, 2000, 20,   70},
{"freeangel",        "`WFreed Angel`x",        TRUE,  TRUE, RACE_FREEANGEL,       5,  TRUE, FALSE,  100, 2000, 18,   70},
{"godchild",         "`CGod Child`x",          TRUE,  TRUE, RACE_GODCHILD,        5,  TRUE, FALSE,  300, 2000, 25,   70},
{"faechild",         "`GFae Child`x",          TRUE,  TRUE, RACE_FAECHILD,        5,  TRUE, FALSE,  300, 2000, 18,   50},
{"demon",            "demon",                 FALSE, FALSE, RACE_DEMON,          10,  TRUE, FALSE,  100, 2000, 18,   70},
{"faculty",          "`WInstitute Staff`x",    TRUE,  TRUE, RACE_FACULTY,         1,  TRUE,  TRUE,   18, 5000, 18, 5000},
{"animal",           "Animal",                FALSE, FALSE, RACE_ANIMAL,          1, FALSE, FALSE,    0,   99,  0,   99},
{"wight",            "`DWight`x",              TRUE, FALSE, RACE_WIGHT,           2,  TRUE, FALSE,   18, 1000, 18,   99},
{"dabbler",          "`YDabbler`x",            TRUE, FALSE, RACE_DABBLER,         2, FALSE, FALSE,   25,   99, 22,  100},
{"reptile",          "Reptile",               FALSE, FALSE, RACE_REPTILE,         1, FALSE, FALSE,    0, 1000,  0, 1000},
{"insect",           "Insect",                FALSE, FALSE, RACE_INSECT,          1, FALSE, FALSE,    0, 1000,  0, 1000},
{"vegetation",       "Vegetation",            FALSE, FALSE, RACE_VEGETATION,      1, FALSE, FALSE,    0, 1000,  0, 1000},
{"landmonster",      "`gLand Monster`x",       TRUE, FALSE, RACE_LANDMONSTER,     5,  TRUE, FALSE,    0, 2000,  0, 2000},
{"seamonster",       "`BSea Monster`x",        TRUE, FALSE, RACE_SEAMONSTER,      5,  TRUE, FALSE,    0, 2000,  0, 2000},
{"normal",           "Normal",                FALSE, FALSE, RACE_NORMAL,          1,  TRUE, FALSE,    0, 1000,  0, 1000},
{"dreamchild",       "`cDreamchild`x",         TRUE,  TRUE, RACE_DREAMCHILD,      2, FALSE, FALSE,   18,   80, 18,   80},
{"fantasy",          "`cFantasy`x",            TRUE,  TRUE, RACE_FANTASY,         1, FALSE, FALSE,   18,   80, 18,   80},
{"faespirit",        "`gFae Spirit`x",         TRUE, FALSE, RACE_SPIRIT_FAE,      6,  TRUE, FALSE,   20, 5000, 18,   80},
{"divinespirit",     "`cDivine Spirit`x",      TRUE, FALSE, RACE_SPIRIT_DIVINE,   6,  TRUE, FALSE,   20, 5000, 18,   80},
{"demonspirit",      "`rDemon Spirit`x",       TRUE, FALSE, RACE_SPIRIT_DEMON,    6,  TRUE, FALSE,   20, 5000, 18,   80},
{"elseborn",         "`gElseborn`x",           TRUE,  TRUE, RACE_ELSEBORN,        2, FALSE, FALSE,   18,   80, 18,   80},
{"ghostspirit",      "`DGhost Spirit`x",       TRUE, FALSE, RACE_SPIRIT_GHOST,    6,  TRUE, FALSE,   20, 5000, 18,   80},
{"cthulianspirit",   "`gCthulian Spirit`x",    TRUE, FALSE, RACE_SPIRIT_CTHULIAN, 6,  TRUE, FALSE,   20, 5000, 18,   80},
{"primalspirit",     "`yPrimal Spirit`x",      TRUE, FALSE, RACE_SPIRIT_PRIMAL,   6,  TRUE, FALSE,   20, 5000, 18,   80},
};

const struct cliquerole_type cliquerole_table[] = {
{CLIQUEROLE_NONE,         "Loner",        CLIQUE_NONE},
{CLIQUEROLE_DRUGGIE,      "Druggie",     CLIQUE_REBEL},
{CLIQUEROLE_BULLY,        "Bully",       CLIQUE_REBEL},
{CLIQUEROLE_HACKER,       "Hacker",       CLIQUE_NERD},
{CLIQUEROLE_OVERACHIEVER, "Overachiever", CLIQUE_NERD},
{CLIQUEROLE_ARTIST,       "Artist",       CLIQUE_NERD},
{CLIQUEROLE_GOTH,         "Goth",         CLIQUE_NERD},
{CLIQUEROLE_PREP,         "Prep",      CLIQUE_POPULAR},
{CLIQUEROLE_JOCK,         "Jock",      CLIQUE_POPULAR},
};

const struct modifier_type modifier_table[] = {
{0,                    "None",                 0},
{MODIFIER_ADDICTION,   "Addicted",            -1},
{MODIFIER_INJURY,      "Injured",             -1},
{MODIFIER_ILLNESS,     "Ill",                 -1},
{MODIFIER_CRIPPLED,    "Crippled",            -1},
{MODIFIER_DISFIGURED,  "Disfigured",          -1},
{MODIFIER_CURSED,      "Cursed",              -1},
{MODIFIER_INSANE,      "Mentally Ill",        -1},
{MODIFIER_CATATONIC,   "Catatonic",           -1},
{MODIFIER_RELIC,       "Relic Holder",         1},
{MODIFIER_PACT,        "Demonic Pact Holder",  1},
{MODIFIER_CHEMICAL,    "Chemically Augmented", 1},
{MODIFIER_TEMPLE,      "Science Augmented",    1},
{MODIFIER_FLESHFORMED, "Fleshformed",          1},
{MODIFIER_UNLIVING,    "Unliving",             1},
{MODIFIER_LUNACY,      "Lunacy Embracer",      1},
{MODIFIER_DRINKING,    "Exsanguinating",       1},
{MODIFIER_NEW,         "Newly Transformed",   -1},
{MODIFIER_STRONG,      "Strong Bloodline",     1}
};

const struct skill_type skill_table[] = {
{SKILL_REGEN,              "Regeneration",          { 1, 3, 0, 0, 0, 0}},
{SKILL_NIGHTVISION,        "Night Vision",          { 1, 2, 3, 4, 5, 0}},
{SKILL_TELEPATHY,          "Telepathy",             { 2, 0, 0, 0, 0, 0}},
{SKILL_ATTRACTIVENESS,     "Attractiveness",        {-1, 1, 0, 0, 0, 0}},
{SKILL_HYPNOTISM,          "Hypnotism",             { 1, 2, 3, 4, 0, 0}},
{SKILL_WEALTH,             "Wealth",                {-1, 1, 2, 3, 4, 5}},
{SKILL_DARKSORC,           "Dark Sorcery",          { 2, 0, 0, 0, 0, 0}},
{SKILL_FIRESORC,           "Fire Sorcery",          { 2, 0, 0, 0, 0, 0}},
{SKILL_ICESORC,            "Ice Sorcery",           { 2, 0, 0, 0, 0, 0}},
{SKILL_LIGHTNINGSORC,      "Lightning Sorcery",     { 2, 0, 0, 0, 0, 0}},
{SKILL_VIRGIN,             "Virgin",                { 1, 2, 0, 0, 0, 0}},
{SKILL_FLIGHT,             "Flight",                { 3, 0, 0, 0, 0, 0}},
{SKILL_SUPERJUMP,          "Super Jumping",         { 2, 0, 0, 0, 0, 0}},
{SKILL_STRENGTH,           "Strength",              {-1, 1, 2, 3, 4, 5}},
{SKILL_DEXTERITY,          "Dexterity",             {-1, 1, 2, 3, 0, 0}},
{SKILL_ACROBATICS,         "Acrobatics",            {-1, 1, 2, 3, 0, 0}},
{SKILL_RUNNING,            "Running",               { 1, 2, 3, 4, 5, 0}},
{SKILL_EDUCATION,          "Education",             {-1, 1, 2, 3, 4, 5}},
{SKILL_CHARISMA,           "Politics",              { 1, 2, 3, 4, 5, 0}},
{SKILL_FAME,               "Fame",                  { 1, 3, 5, 0, 0, 0}},
{SKILL_LANGUAGE2,          "Second Language",       { 1, 2, 3, 0, 0, 0}},
{SKILL_LANGUAGE3,          "Third Language",        { 1, 2, 3, 0, 0, 0}},
{SKILL_LANGUAGE4,          "Fourth Language",       { 1, 2, 3, 0, 0, 0}},
{SKILL_LANGUAGE5,          "Fifth Language",        { 1, 2, 3, 0, 0, 0}},
{SKILL_ART,                "Artistic Ability",      { 1, 3, 5, 0, 0, 0}},
{SKILL_ART2,               "Second Art",            { 1, 3, 5, 0, 0, 0}},
{SKILL_ART3,               "Third Art",             { 1, 3, 5, 0, 0, 0}},
{SKILL_CAR,                "Car",                   { 1, 2, 3, 4, 5, 0}},
{SKILL_DODGING,            "Melee Defense",         {-1, 1, 2, 3, 4, 5}},
{SKILL_EVADING,            "Ranged Defense",        {-1, 1, 2, 3, 4, 5}},
{SKILL_CPOLICE,            "Police",                { 1, 2, 3, 4, 5, 0}},
{SKILL_CMILITARY,          "Military",              { 1, 2, 3, 4, 5, 0}},
{SKILL_CGOVERNMENT,        "Government",            { 1, 2, 3, 4, 5, 0}},
{SKILL_CMEDIA,             "Media",                 { 1, 2, 3, 4, 5, 0}},
{SKILL_CCRIMINAL,          "Underworld",            { 1, 2, 3, 4, 5, 0}},
{SKILL_CHOMELESS,          "Homeless",              { 1, 2, 3, 4, 5, 0}},
{SKILL_COCCULT,            "Occult",                { 1, 2, 3, 4, 5, 0}},
{SKILL_ENDOWMENT,          "College Endowment",     { 3, 0, 0, 0, 0, 0}},
{SKILL_DEMOLITIONS,        "Demolitions",           { 1, 2, 3, 0, 0, 0}},
{SKILL_HACKING,            "Hacking",               { 1, 2, 3, 4, 5, 0}},
{SKILL_STEALTH,            "Stealth",               { 1, 2, 3, 4, 5, 0}},
{SKILL_PERCEPTION,         "Perception",            { 1, 2, 3, 4, 5, 0}},
{SKILL_MEDICINE,           "Medicine",              { 1, 2, 3, 4, 5, 0}},
{SKILL_DEMONOLOGY,         "Occult Knowledge",      { 1, 2, 3, 4, 5, 0}},
{SKILL_ENGINEERING,        "Engineering",           { 1, 2, 3, 4, 5, 0}},
{SKILL_HANDYMAN,           "Handyman",              { 1, 2, 3, 4, 5, 0}},
{SKILL_STAMINA,            "Stamina",               {-1, 1, 2, 3, 4, 5}},
{SKILL_LARCENY,            "Larceny",               { 1, 2, 3, 4, 5, 0}},
{SKILL_ANIMALS,            "Animals",               { 1, 2, 3, 4, 5, 0}},
{SKILL_MARTIALART,         "Melee Attack",          { 1, 2, 3, 4, 5, 0}},
{SKILL_COMBATTRAINING,     "Ranged Attack",         { 1, 2, 3, 4, 5, 0}},
{SKILL_FASTREFLEXES,       "Fast Reflexes",         { 1, 2, 3, 0, 0, 0}},
{SKILL_ACUTESIGHT,         "Acute Sight",           { 1, 0, 0, 0, 0, 0}},
{SKILL_ACUTESMELL,         "Acute Smell",           { 1, 0, 0, 0, 0, 0}},
{SKILL_ACUTEHEAR,          "Acute Hearing",         { 1, 0, 0, 0, 0, 0}},
{SKILL_KNOWVAMP,           "Know Vampires",         { 2, 0, 0, 0, 0, 0}},
{SKILL_KNOWWERE,           "Know Werewolves",       { 2, 0, 0, 0, 0, 0}},
{SKILL_KNOWMAGE,           "Know Super",            { 2, 0, 0, 0, 0, 0}},
{SKILL_AGELESS,            "Ageless",               { 4, 0, 0, 0, 0, 0}},
{SKILL_ALLIES,             "Allies",                { 1, 2, 3, 4, 5, 0}},
{SKILL_MINIONS,            "Minions",               { 1, 2, 3, 4, 5, 0}},
{SKILL_BIKE,               "Motorcycle",            { 1, 2, 3, 4, 5, 0}},
{SKILL_ARTAMULET,          "Artificing Amulets",    { 1, 2, 3, 4, 5, 0}},
{SKILL_GAMES,              "Games",                 { 1, 2, 3, 0, 0, 0}},
{SKILL_DEMIGOD,            "Demigod",               { 1, 0, 0, 0, 0, 0}},
{SKILL_TIMESWEPT,          "Timeswept",             { 1, 0, 0, 0, 0, 0}},
{SKILL_FAEBORN,            "Faeborn",               { 1, 0, 0, 0, 0, 0}},
{SKILL_DEMONBORN,          "Demonborn",             { 1, 0, 0, 0, 0, 0}},
{SKILL_ANGELBORN,          "Angelborn",             { 1, 0, 0, 0, 0, 0}},
{SKILL_OBFUSCATE,          "Obfuscate",             { 2, 0, 0, 0, 0, 0}},
{SKILL_TELEMPATHY,         "Telempathy",            { 2, 0, 0, 0, 0, 0}},
{SKILL_LIGHTUP,            "Lightup",               { 1, 0, 0, 0, 0, 0}},
{SKILL_ELECTROPATHIC,      "Electropathic",         { 2, 0, 0, 0, 0, 0}},
{SKILL_CLAIRVOYANCE,       "Clairvoyance",          { 1, 2, 0, 0, 0, 0}},
{SKILL_CLAIRAUDIENCE,      "Clairaudience",         { 2, 0, 0, 0, 0, 0}},
{SKILL_SHAPESHIFTING,      "Shapeshifting",         { 1, 2, 3, 4, 5, 0}},
{SKILL_HYPERSHIFTING,      "Mythological Shifting", { 2, 0, 0, 0, 0, 0}},
{SKILL_AURASHIFTING,       "Aura Shifting",         { 3, 0, 0, 0, 0, 0}},
{SKILL_METASHIFTING,       "Meta Shifting",         { 4, 0, 0, 0, 0, 0}},
{SKILL_SENSEBLOOD,         "Sense Blood",           { 1, 0, 0, 0, 0, 0}},
{SKILL_FACESTEALING,       "Face Stealing",         { 2, 0, 0, 0, 0, 0}},
{SKILL_SILVERVULN,         "Silver Vulnerability",  { 1, 0, 0, 0, 0, 0}},
{SKILL_GOLDVULN,           "Gold Vulnerability",    { 1, 0, 0, 0, 0, 0}},
{SKILL_GHOSTWALKING,       "Ghost Walking",         { 4, 0, 0, 0, 0, 0}},
{SKILL_RITUALISM,          "Ritualism",             { 1, 2, 3, 4, 5, 0}},
{SKILL_ILLUSIONS,          "Illusions",             { 2, 0, 0, 0, 0, 0}},
{SKILL_FORENSICS,          "Forensics",             { 2, 0, 0, 0, 0, 0}},
{SKILL_DREAMING,           "Dream Invading",        { 2, 0, 0, 0, 0, 0}},
{SKILL_PRISSORC,           "Prismatic Sorcery",     { 2, 0, 0, 0, 0, 0}},
{SKILL_BONEVULN,           "Bone Vulnerability",    { 1, 0, 0, 0, 0, 0}},
{SKILL_WOODVULN,           "Wood Vulnerability",    { 1, 0, 0, 0, 0, 0}},
{SKILL_HYPERSTRENGTH,      "Epic Strength",         { 2, 0, 0, 0, 0, 0}},
{SKILL_HYPERREFLEXES,      "Hypernatural Reflexes", { 2, 0, 0, 0, 0, 0}},
{SKILL_HYPERSPEED,         "Blurring Speed",        { 2, 0, 0, 0, 0, 0}},
{SKILL_SWARMSHIFTING,      "Swarm Shifting",        { 2, 0, 0, 0, 0, 0}},
{SKILL_HYBRIDSHIFTING,     "Hybrid Shifting",       { 2, 0, 0, 0, 0, 0}},
{SKILL_CUSTOM,             "Custom",                { 2, 0, 0, 0, 0, 0}},
{SKILL_WINGS,              "Wings",                 { 2, 0, 0, 0, 0, 0}},
{SKILL_MONSTERSHIFT,       "Monstrous Shifting",    { 2, 0, 0, 0, 0, 0}},
{SKILL_BRANDING,           "Branding",              { 2, 0, 0, 0, 0, 0}},
{SKILL_GUARDEDMIND,        "Guarded Mind",          { 3, 0, 0, 0, 0, 0}},
{SKILL_ARMORED,            "Armored",               { 2, 0, 0, 0, 0, 0}},
{SKILL_OCCULTFOCUS,        "Occultist",             { 1, 2, 3, 0, 0, 0}},
{SKILL_MESMERIZING,        "Mesmerizing",           { 3, 0, 0, 0, 0, 0}},
{SKILL_HYPERREGEN,         "Hypernatural Regen",    { 3, 0, 0, 0, 0, 0}},
{SKILL_MISTVISION,         "Mist Vision",           { 1, 0, 0, 0, 0, 0}},
{SKILL_DREAMSTALK,         "Dream Stalking",        { 1, 0, 0, 0, 0, 0}},
{SKILL_FLESHFORMED,        "Fleshformed",           { 1, 0, 0, 0, 0, 0}},
{SKILL_GADGETS,            "Gadgets",               { 2, 3, 0, 0, 0, 0}},
{SKILL_MARTIAL,            "Martial Arts",          { 2, 3, 0, 0, 0, 0}},
{SKILL_SOLDIER,            "Soldiering",            { 2, 3, 0, 0, 0, 0}},
{SKILL_COMMANDO,           "Commando",              { 2, 3, 0, 0, 0, 0}},
{SKILL_RIOT,               "Riot Control",          { 2, 3, 0, 0, 0, 0}},
{SKILL_NATURE,             "Nature Mancing",        { 1, 2, 0, 0, 0, 0}},
{SKILL_PSYCHIC,            "Psychic",               { 1, 2, 0, 0, 0, 0}},
{SKILL_COMBAT_ILLUSIONS,   "Illusory Mancing",      { 1, 2, 0, 0, 0, 0}},
{SKILL_HAEMOMANCY,         "Haemomancy",            { 1, 2, 0, 0, 0, 0}},
{SKILL_TELEKINESIS,        "Telekinesis",           { 1, 2, 0, 0, 0, 0}},
{SKILL_WEATHER,            "Weather Mancing",       { 1, 2, 0, 0, 0, 0}},
{SKILL_MAGNO,              "Magnokinesis",          { 1, 2, 0, 0, 0, 0}},
{SKILL_BIOMANCY,           "Biokinesis",            { 1, 2, 0, 0, 0, 0}},
{SKILL_CRYO,               "Cryomancy",             { 1, 2, 0, 0, 0, 0}},
{SKILL_PYRO,               "Pyromancy",             { 1, 2, 0, 0, 0, 0}},
{SKILL_NECRO,              "Necromancy",            { 1, 2, 0, 0, 0, 0}},
{SKILL_MINDREADING,        "Mind Reading",          { 2, 0, 0, 0, 0, 0}},
{SKILL_CRYPTOMIND,         "Cryptographic Mind",    { 2, 0, 0, 0, 0, 0}},
{SKILL_MEMORYCLOAK,        "Memory Cloak",          { 2, 0, 0, 0, 0, 0}},
{SKILL_ENTHRALL,           "Enthrall",              { 2, 0, 0, 0, 0, 0}},
{SKILL_ENRAPTURE,          "Enrapture",             { 2, 0, 0, 0, 0, 0}},
{SKILL_SEEKPREY,           "Seek Prey",             { 1, 0, 0, 0, 0, 0}},
{SKILL_SUNRESIST,          "Sunlight",              { 3, 0, 0, 0, 0, 0}},
{SKILL_ICEPROOF,           "Frost",                 { 2, 0, 0, 0, 0, 0}},
{SKILL_FIREPROOF,          "Fire",                  { 2, 0, 0, 0, 0, 0}},
{SKILL_ELECPROOF,          "Electricity",           { 2, 0, 0, 0, 0, 0}},
{SKILL_IMMORTALITY,        "Immortality",           { 2, 0, 0, 0, 0, 0}},
{SKILL_FLESHFORMING,       "Fleshforming",          { 4, 0, 0, 0, 0, 0}},
{SKILL_MIMIC,              "Mimic",                 { 2, 0, 0, 0, 0, 0}},
{SKILL_RITUALPROOF,        "Magic Resistance",      { 2, 0, 0, 0, 0, 0}},
{SKILL_HYPERPERCEPTION,    "Hyper Perception",      { 2, 0, 0, 0, 0, 0}},
{SKILL_RESURRECTION,       "Resurrection",          { 4, 0, 0, 0, 0, 0}},
{SKILL_SHADOWCLOAK,        "Shadow Cloak",          { 2, 0, 0, 0, 0, 0}},
{SKILL_CLOUDSUMMON,        "Cloud Summoning",       { 1, 2, 0, 0, 0, 0}},
{SKILL_FAEKNIGHTFOCUS,     "Fae Knight",            { 1, 2, 3, 4, 0, 0}},
{SKILL_DEMONWARRIORFOCUS,  "Demon Warrior",         { 1, 2, 3, 4, 0, 0}},
{SKILL_ANGELCHAMPIONFOCUS, "Angelborn Champion",    { 1, 2, 3, 4, 0, 0}},
{SKILL_DEMIWARRIORFOCUS,   "Demigod Warrior",       { 1, 2, 3, 4, 0, 0}},
{SKILL_BLADEDISCFOCUS,     "Blade Disciple",        { 1, 2, 3, 4, 0, 0}},
{SKILL_GUNDISCFOCUS,       "Gun Disciple",          { 1, 2, 3, 4, 0, 0}},
{SKILL_PRIMALFOCUS,        "Primal",                { 1, 2, 3, 4, 0, 0}},
{SKILL_WARRIORFOCUS,       "Warrior",               { 1, 2, 3, 0, 0, 0}},
{SKILL_SOLDIERFOCUS,       "Soldier",               { 1, 2, 3, 0, 0, 0}},
{SKILL_ASSASSINFOCUS,      "Hunter",                { 1, 2, 3, 0, 0, 0}},
{SKILL_ILLUSORYMAGICFOCUS, "Illusory Magic",        { 1, 2, 3, 4, 0, 0}},
{SKILL_NATURALMAGICFOCUS,  "Natural Magic",         { 1, 2, 3, 4, 0, 0}},
{SKILL_DARKMAGICFOCUS,     "Dark Magic",            { 1, 2, 3, 4, 0, 0}},
{SKILL_ELEMAGICFOCUS,      "Elemental Magic",       { 1, 2, 3, 4, 0, 0}},
{SKILL_BUSINESSFOCUS,      "Business Person",       { 1, 2, 3, 4, 0, 0}},
{SKILL_GENERALFOCUS,       "Commander",             { 1, 2, 3, 4, 0, 0}},
{SKILL_MOGULFOCUS,         "Underworld Mogul",      { 1, 2, 3, 4, 0, 0}},
{SKILL_SOCIALFOCUS,        "Socialite",             { 1, 2, 3, 4, 0, 0}},
{SKILL_SCIENCEFOCUS,       "Scientist",             { 1, 2, 3, 0, 0, 0}},
{SKILL_THIEFFOCUS,         "Thief",                 { 1, 2, 3, 0, 0, 0}},
{SKILL_ENGINEERFOCUS,      "Engineer",              { 1, 2, 3, 0, 0, 0}},
{SKILL_SEDUCE,             "Demonic Seduction",     { 1, 0, 0, 0, 0, 0}},
{SKILL_ENRAGE,             "Enrage",                { 1, 0, 0, 0, 0, 0}},
{SKILL_RAGEFUELED,         "Rage Fueled",           { 1, 0, 0, 0, 0, 0}},
{SKILL_NIGHTMARE,          "Nightmares",            { 1, 0, 0, 0, 0, 0}},
{SKILL_WAILING,            "Demonic Cry",           { 1, 0, 0, 0, 0, 0}},
{SKILL_STORMCALLING,       "Storm Calling",         { 1, 0, 0, 0, 0, 0}},
{SKILL_OCEANAFFINITY,      "One with the Waves",    { 1, 0, 0, 0, 0, 0}},
{SKILL_SOLARBLESS,         "Solar Blessing",        { 1, 0, 0, 0, 0, 0}},
{SKILL_LUNARBLESS,         "Lunar Blessing",        { 1, 0, 0, 0, 0, 0}},
{SKILL_DEATHTOUCH,         "Underworld Touch",      { 1, 0, 0, 0, 0, 0}},
{SKILL_WARBLESS,           "Blessing of Battle",    { 1, 0, 0, 0, 0, 0}},
{SKILL_FERTILITY,          "Lover's Blessing",      { 1, 0, 0, 0, 0, 0}},
{SKILL_LUCKCHANGE,         "Luck Changing",         { 1, 0, 0, 0, 0, 0}},
{SKILL_MERSHIFTER,         "Mershifter",            { 1, 0, 0, 0, 0, 0}},
{SKILL_BLOOMING,           "Floral Blessing",       { 1, 0, 0, 0, 0, 0}},
{SKILL_SIRENSONG,          "Song of the Sirens",    { 1, 0, 0, 0, 0, 0}},
{SKILL_SENSEWEAKNESS,      "Sense Weakness",        { 1, 0, 0, 0, 0, 0}},
{SKILL_GUARDIAN,           "Guardian Angel",        { 1, 0, 0, 0, 0, 0}},
{SKILL_FLEETFOOT,          "Fleet of Foot",         { 1, 0, 0, 0, 0, 0}},
{SKILL_SOOTHING,           "Soothing Aura",         { 1, 0, 0, 0, 0, 0}},
{SKILL_TOUCHED,            "Sensitive",             { 1, 0, 0, 0, 0, 0}},
{SKILL_CHAND,              "Hand",                  { 1, 2, 3, 4, 5, 0}},
{SKILL_CORDER,             "Order",                 { 1, 2, 3, 4, 5, 0}},
{SKILL_CTEMPLE,            "Temple",                { 1, 2, 3, 4, 5, 0}},
{SKILL_CSUBFACTION,        "Subfaction",            { 1, 2, 3, 4, 5, 0}},
{SKILL_ALCHEMY,            "Alchemy",               { 1, 2, 3, 4, 5, 0}},
{SKILL_CONDITIONING,       "Physical Conditioning", { 1, 2, 3, 4, 5, 6}},
{SKILL_BEAUTY,             "Beauty Rituals",        { 1, 2, 3, 4, 5, 6}},
{SKILL_FASHION,            "Fashion Knowledge",     { 1, 2, 3, 4, 5, 6}},
{SKILL_INCANTATION,        "Incantation",           { 1, 2, 3, 4, 0, 0}},
{SKILL_ANGELCOMBAT,        "Angelic Combat",        { 1, 2, 0, 0, 0, 0}},
{SKILL_DAYASPECT,          "Aspects of Day",        { 1, 2, 0, 0, 0, 0}},
{SKILL_NIGHTASPECT,        "Aspects of Night",      { 1, 2, 0, 0, 0, 0}},
{SKILL_PRIMALCOMBAT,       "Primal Combat",         { 1, 2, 0, 0, 0, 0}},
{SKILL_GLIDE,              "Glide",                 { 3, 0, 0, 0, 0, 0}},
{SKILL_FLUIDSHIFT,         "Fluid Shifting",        { 3, 0, 0, 0, 0, 0}},
{SKILL_DUALASPECT,         "Dual Aspects",          { 3, 0, 0, 0, 0, 0}},
{SKILL_DEMONMETABOL,       "Demonic Metabolism",    { 3, 0, 0, 0, 0, 0}},
{SKILL_VICIOUSSTRIKES,     "Vicious Strikes",       { 3, 0, 0, 0, 0, 0}},
{SKILL_BLADEDEFENSE,       "Blade Defense",         { 3, 0, 0, 0, 0, 0}},
{SKILL_QUICKRELOAD,        "Quick Reload",          { 2, 0, 0, 0, 0, 0}},
{SKILL_ILLUSORYAFFINITY,   "Illusory Affinity",     { 3, 0, 0, 0, 0, 0}},
{SKILL_NATURALAFFINITY,    "Natural Affinity",      { 3, 0, 0, 0, 0, 0}},
{SKILL_MAGICOVERLOAD,      "Magical Overload",      { 3, 0, 0, 0, 0, 0}},
{SKILL_DUALELEMENTS,       "Dual Elements",         { 3, 0, 0, 0, 0, 0}},
{SKILL_SNIPERTRAINING,     "Sniper Training",       { 3, 0, 0, 0, 0, 0}},
{SKILL_RIPOSTE,            "Riposte",               { 3, 0, 0, 0, 0, 0}},
{SKILL_PARALYTIC,          "Paralytic Toxin",       { 2, 0, 0, 0, 0, 0}},
{SKILL_POISONTOXIN,        "Poisonous Toxin",       { 2, 0, 0, 0, 0, 0}},
{SKILL_GIANTSLAYER,        "Giant Slayer",          { 2, 0, 0, 0, 0, 0}},
{SKILL_DISPOSABLEMUSCLE,   "Disposable Muscle",     { 2, 0, 0, 0, 0, 0}},
{SKILL_PROTECTIONDETAIL,   "Protection Detail",     { 2, 0, 0, 0, 0, 0}},
{SKILL_MILITARYTRAINING,   "Military Training",     { 2, 0, 0, 0, 0, 0}},
{SKILL_PERSUADE,           "Psychic Persuasion",    { 1, 0, 0, 0, 0, 0}},
{SKILL_PATHING,            "Pathing",               { 2, 3, 4, 0, 0, 0}},
{SKILL_CALLNATURE,         "Call of Nature",        { 2, 0, 0, 0, 0, 0}},
{SKILL_CALLGRAVE,          "Call of the Grave",     { 2, 0, 0, 0, 0, 0}},
{SKILL_ELEMINIONS,         "Elemental Spirits",     { 2, 0, 0, 0, 0, 0}},
{SKILL_POWERARMOR,         "Powered Armor",         { 2, 0, 0, 0, 0, 0}},
{SKILL_FAMOUS,             "Celebrity",             { 2, 0, 0, 0, 0, 0}},
{SKILL_FINANCIALRUIN,      "Financial Ruin",        { 2, 0, 0, 0, 0, 0}},
{SKILL_ARRANGEHIT,         "Arrange Hit",           { 2, 0, 0, 0, 0, 0}},
{SKILL_VIEWSECRETS,        "Find Secrets",          { 2, 0, 0, 0, 0, 0}},
{SKILL_CLINICCONTRACT,     "Clinic Contract",       { 1, 0, 0, 0, 0, 0}},
{SKILL_COLLEGECONTRACT,    "College Contract",      { 1, 0, 0, 0, 0, 0}},
{SKILL_DREAMSIGHT,         "Dream Sight",           { 1, 0, 0, 0, 0, 0}},
{SKILL_SPLITMIND,          "Split Mind",            { 1, 2, 0, 0, 0, 0}},
{SKILL_COLDSPEC,           "Cold Specialization",   { 1, 0, 0, 0, 0, 0}},
{SKILL_HOTSPEC,            "Hot Specialization",    { 1, 0, 0, 0, 0, 0}}
};

const struct discipline_type discipline_table[] = {
{DIS_TELEKINESIS, "Telekinesis",        50, 0},
{DIS_PISTOLS,     "Pistols",            70, 1},
{DIS_THROWN,      "Thrown Weapons",     40, 1},
{DIS_BOWS,        "Bows",               90, 1},
{DIS_ENERGY,      "Energy Sorcery",    100, 0},
{DIS_FIRE,        "Fire Sorcery",      100, 0},
{DIS_ICE,         "Ice Sorcery",       110, 0},
{DIS_LIGHTNING,   "Lightning Sorcery",  90, 0},
{DIS_DARK,        "Dark Sorcery",      100, 0},
{DIS_SHOTGUNS,    "Shotguns",           30, 1},
{DIS_TELEPATHY,   "Psychic Blasts",    140, 0}, // 10
{DIS_SONIC,       "Sonic",              30, 0},
{DIS_RADIATION,   "Radiation",         120, 0},
{DIS_STONE,       "Stone Magic",        60, 0},
{DIS_LONGBLADE,   "Long Blades",         0, 1},
{DIS_STRIKING,    "Striking",            0, 1},
{DIS_KNIFE,       "Short Blades",        0, 1},
{DIS_CLAW,        "Tooth and Claw",      0, 0},
{DIS_ENERGYF,     "Energy Fighting",     0, 0},
{DIS_FIREF,       "Fire Fighting",       0, 0},
{DIS_ICEF,        "Ice Fighting",        0, 0}, // 20
{DIS_LIGHTNINGF,  "Lightning Fighting",  0, 0},
{DIS_DARKF,       "Dark Fighting",       0, 0},
{DIS_BRUTE,       "Brute Force",         0, 0},
{DIS_BARMOR,      "Ballistic Armor",    -1, 1},
{DIS_MARMOR,      "Medieval Armor",     -1, 1},
{DIS_NARMOR,      "Natural Armor",      -1, 0},
{DIS_TOUGHNESS,   "Natural Toughness",  -1, 1},
{DIS_ENERGYS,     "Energy Shield",      -1, 0},
{DIS_FIRES,       "Fire Shield",        -1, 0},
{DIS_ICES,        "Ice Shield",         -1, 0}, // 30
{DIS_LIGHTNINGS,  "Lightning Shield",   -1, 0},
{DIS_STONES,      "Stone Shield",       -1, 0},
{DIS_MENTALS,     "Mental Shield",      -1, 0},
{DIS_DARKS,       "Dark Shield",        -1, 0},
{DIS_WEATHER,     "Weather",           100, 0},
{DIS_NATURE,      "Nature",            100, 0},
{DIS_WOODS,       "Wood Shield",        -1, 0},
{DIS_CUSTOM,      "Custom",            100, 0},
{DIS_RIFLES,      "Rifles",            110, 1},
{DIS_CARBINES,    "Carbines",          100, 1}, // 40
{DIS_BLUNT,       "Blunt Weapons",       0, 1},
{DIS_HELLFIRE,    "Hellfire",          100, 0},
{DIS_SHADOWL,     "Shadow Lightning",  100, 0},
{DIS_GRAPPLE,     "Grappling",           0, 1},
{DIS_BONES,       "Reinforced Bones",   -1, 1},
{DIS_FORCES,      "Force Shield",       -1, 1},
{DIS_UNDEAD,      "Undead Toughness",   -1, 1},
{DIS_FATE,        "Fate's Protection",  -1, 1},
{DIS_PUSH,        "Force Protection",   -1, 1},
{DIS_BSHIELD,     "Ballistic Shields",  -1, 1},
{DIS_MSHIELD,     "Medieval Shields",   -1, 1},
{DIS_PRISMATIC,   "Prismatic Sorcery", 100, 0},
{DIS_SPEAR,       "Spears",              0, 1},
{DIS_SPEARGUN,    "Spearguns",          60, 1}
};

const struct special_type special_table[] = {
{SPECIAL_STUN,       "Stun",        0},
{SPECIAL_KNOCKBACK,  "Knockback",   0},
{SPECIAL_ENTRAP,     "Entrap",      0},
{SPECIAL_GRAPPLE,    "Grapple",     0},
{SPECIAL_LIFESTEAL,  "StealLife",   0},
{SPECIAL_DELAY,      "Delayed",     1},
{SPECIAL_DELAY2,     "LongDelayed", 1},
{SPECIAL_OVERPOWER,  "Overpower",   1},
{SPECIAL_DAMAGE,     "Damage",      0},
{SPECIAL_WEAKEN,     "Weaken",      0},
{SPECIAL_UNDERPOWER, "Underpower",  1},
{SPECIAL_LONGWEAKEN, "LongWeaken",  0},
{SPECIAL_SLOW,       "Slow",        0},
{SPECIAL_AOE,        "Aoe",         1},
{SPECIAL_WOUND,      "Wounding",    1}
};

const struct industry_type industry_table[] = {
{INDUSTRY_NONE,          "none",                1,  1, 100},
{INDUSTRY_CONSTRUCTION,  "construction",        6, 10, 100},
{INDUSTRY_ONLINE,        "online",              3,  2,  80},
{INDUSTRY_STORE,         "store",               3,  5, 100},
{INDUSTRY_RESTAURANT,    "restaurant",          5,  6,  90},
{INDUSTRY_CLOTHES,       "clothes and fashion", 4,  5, 100},
{INDUSTRY_BAR,           "bar",                 6,  4,  80},
{INDUSTRY_CLUB,          "club",                6,  4,  80},
{INDUSTRY_SECURITY,      "security",            3,  4, 100},
{INDUSTRY_INVESTIGATION, "investigation",       3,  4, 100},
{INDUSTRY_RESIDENCE,     "residence",           3,  3,  90},
{INDUSTRY_FINANCIAL,     "financial",           5,  3, 120},
{INDUSTRY_NONPROFIT,     "nonprofit",           4,  7, 120},
{INDUSTRY_RESEARCH,      "research",            3,  5, 120},
{INDUSTRY_PRIMARY,       "primary industry",    6, 10, 100},
{INDUSTRY_FACTORY,       "factory",             4,  7, 100},
{INDUSTRY_EDUCATION,     "education",           3,  5, 120},
{INDUSTRY_HOSPITALITY,   "hospitality",         4,  6, 110},
{INDUSTRY_MSERVICE,      "mobile service",      3,  5,  90},
{INDUSTRY_SSERVICE,      "static service",      4,  7,  95},
{INDUSTRY_AGRICULTURE,   "agriculture",         6, 10, 100},
{INDUSTRY_CAFE,          "cafe",                4,  5,  90},
{INDUSTRY_TAKEOUT,       "takeout",             4,  5,  90},
{INDUSTRY_TRANSPORT,     "transport",           5,  7, 100},
{INDUSTRY_SEX,           "sex",                 5,  6,  80},
{INDUSTRY_LEGAL,         "legal",               3,  3, 120},
{INDUSTRY_ARTIST,        "arts and crafts",     3,  1,  80},
{INDUSTRY_TECHNOLOGY,    "technology",          5,  4, 120},
{INDUSTRY_JOURNALISM,    "journalism",          4,  5, 100},
{INDUSTRY_GAMES,         "games/gaming",        4,  5, 100},
{INDUSTRY_HEAD,          "head shop",           3,  4, 100},
{INDUSTRY_BEAUTY,        "beauty",              3,  4, 100}
};

const struct monster_type monster_table[] = {
{10, WORLD_OTHER,    CAPTURE_TORMENT, 0, "kobold's gall bladder"},
{11, WORLD_WILDS,    CAPTURE_EAT,     0, "rat claws"},
{12, WORLD_OTHER,    CAPTURE_KIDNAP,  0, "hound's heart"},
{13, WORLD_OTHER,    CAPTURE_TORMENT, 1, "bone necklace"},
{14, WORLD_OTHER,    CAPTURE_EGGS,    0, "living seed"},
{15, WORLD_OTHER,    CAPTURE_TORMENT, 0, "black eyes"},
{16, WORLD_OTHER,    CAPTURE_EAT,     0, "wooden heart"},
{17, WORLD_OTHER,    CAPTURE_TURN,    0, "ghoul brain"},
{18, WORLD_OTHER,    CAPTURE_KIDNAP,  0, "stone heart"},
{19, WORLD_OTHER,    CAPTURE_KIDNAP,  1, "reed necklace"},
{20, WORLD_OTHER,    CAPTURE_KIDNAP,  0, "stone eyes"},
{21, WORLD_GODREALM, CAPTURE_EAT,     0, "griffon pelt"},
{22, WORLD_GODREALM, CAPTURE_EAT,     0, "minotaur horn"},
{23, WORLD_GODREALM, CAPTURE_EAT,     0, "manticore venom"},
{24, WORLD_GODREALM, CAPTURE_EAT,     0, "wyvern's tailtip"},
{25, WORLD_GODREALM, CAPTURE_EAT,     1, "bone necklace"},
{26, WORLD_GODREALM, CAPTURE_TORMENT, 0, "gorgon's serpent hair"},
{27, WORLD_GODREALM, CAPTURE_EGGS,    0, "serpent's fangs"},
{28, WORLD_GODREALM, CAPTURE_KIDNAP,  1, "black metal dagger"},
{29, WORLD_GODREALM, CAPTURE_TURN,    1, "gold necklace"},
{30, WORLD_HELL,     CAPTURE_TORMENT, 0, "demon heart"},
{31, WORLD_HELL,     CAPTURE_TORMENT, 0, "demon heart"},
{32, WORLD_HELL,     CAPTURE_TORMENT, 0, "black tentacle"},
{33, WORLD_HELL,     CAPTURE_TORMENT, 0, "demon heart"},
{34, WORLD_HELL,     CAPTURE_KIDNAP,  0, "hellhound fangs"},
{35, WORLD_HELL,     CAPTURE_TORMENT, 0, "demon heart"},
{36, WORLD_WILDS,    CAPTURE_EAT,     0, "dinosaur skin"},
{37, WORLD_WILDS,    CAPTURE_EAT,     0, "boar tusks"},
{38, WORLD_WILDS,    CAPTURE_EGGS,    0, "spider silkglands"},
{39, WORLD_WILDS,    CAPTURE_EAT,     0, "oversized bat fangs"},
{40, WORLD_WILDS,    CAPTURE_EAT,     0, "white wolf pelt"},
{41, WORLD_WILDS,    CAPTURE_KIDNAP,  1, "stone necklace"},
{42, WORLD_WILDS,    CAPTURE_TURN,    0, "zombie brain"},
{43,          -1,              -1,    0, ""}
};

// This must be at the end of the file - Scaelorn
#if defined(__cplusplus)
}
#endif
